### ISSUE TITLE
Manage server settings and server bootstrapping

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/remote-server#1015]
(To be discussed):
Motivation: provide an UI to let the user enter details such as central server url and side id, e.g. for the initial startup of the Android app.

### General settings management (during normal operation)
- [x] Store server settings (apart from DB connection settings) in the DB
- [x] Option to start the server using the current config file settings (in case settings in the DB are invalid and the server becomes unreachable)
- [x] Endpoint to retrieve server settings from the DB (including currently used settings if differ from the settings in the DB). 
- [x] Endpoint to modify server settings in the DB
- [x] Endpoint to restart the server, e.g. to use the new settings

### Create settings on first startup
- [x] If no settings are available on startup (or settings are incomplete), boot the server into a "stage 0" mode where only endpoints to manage the server settings are provided.
- [x] Relax user permission validation in this mode, e.g. if there is no user yet
- [x] Endpoint to fetch server status, e.g. to determine if server is running in "stage 0" mode

**Comment by andreievg** [comment]
related issue: https://github.com/openmsupply/remote-server/issues/996
