### ISSUE TITLE
master_lists, items, invoice_counts and stock_count queries don't make use of the store_id

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/remote-server#1040]
For example, the master_list endpoint takes a store_id parameter but doesn't filter master_list by this store_id. The endpoint should only return lists for the provided store_id. The MasterListFilterInput filter already has a `exists_for_store_id` option that can be used to filter for the desired lists.

GraphQl entry point for master_list: `graphql/general/src/queries/master_list.rs` (https://github.com/openmsupply/remote-server/pull/1032)

Similar changes have been done recently for the location endpoint: `graphql/location/src/lib.rs` ()

- [x] master_list
- [x] invoice_counts
- [x] stock_count

**Comment by jmbrunskill** [comment]
Items don't seem to have clear relationship to stores in open MSupply at this stage. Will leave them for now.

**Comment by mark-prins** [comment]
> Items don't seem to have clear relationship to stores in open MSupply at this stage. Will leave them for now.

If visibility is controlled by master lists ( and I think now this is the default, and possibly only, approach ), then the relationship is:
- `item` - `master_list_line`
- `master_list_line` - `master_list`
- `master_list` - `master_list_name_join`
- `master_list_name_join` - `store`

for example:

```
select s.code, ml."name", i."name"
from store s
join master_list_name_join mlnj on s.name_id = mlnj.name_id 
join master_list ml on mlnj.master_list_id = ml.id
join master_list_line mll on ml.id = mll.master_list_id 
join item i on mll.item_id = i.id
where s.code like 'Kopu%'
```

😬

**Comment by jmbrunskill** [comment]
@mark-prins So you're saying we do still need to filter items by store? Clemens wasn't sure...

**Comment by mark-prins** [comment]
yes, we do. Items are made visible to specific stores in mSupply currently.
Originally in mSupply, the visibility was store-item but that is tricky to manage.
So when master lists came along, you could control using either by specific item, or using the master list i.e. if the list was visible in a store, you could see all the items on the list.
There's now a preference to control visibility by master list, or individual item ( as store preference, so each store can decide the approach to use). I understand though that the master list approach is preferred, and might be the only way to control visibility in open mSupply.

**Comment by Chris-Petty** [comment]
Just throwing in a few extra notes in:

A big thing improved by not using an `item_store_join` to control visibility is that every _other_ field on that table is store/remote data. In current mSupply we have to fuss with item_store_join getting overwritten by the remote, losing centrally controlled "visibility" field value. Happens regardless of the pref, but with the pref on it also means that the joins can get out of line with what the lists dictate.

Also a lot less overhead to just sync what master lists your customer stores use, rather than every single item_store_join of your customer stores.

In mSupply classic, the preference is global and not per store. Though it could be a store pref, junior developer me did not do that 😁 .

**Comment by mark-prins** [comment]
Thanks Chris!

> In mSupply classic, the preference is global and not per store

ah, right. Item tab: `Automatically update item visibility in all stores to match master lists...` 
I was mislead by the alert "preference for store visibility to match master lists is on" I was reading that as a single store 🙄 

> That said, we still will want item_store_join eventually! 

This usage of a join table storing metadata still feels weird to me and I usually forget about that. To me the table is doing double duty, it's named as a join table and is joining an item to a store.. but is also storing information about the item which is specific to a store. This becomes weirder when the join is actually controlled by a master list.

Would it trouble people if we had an `item_store_details` (properties? metadata?)
Actually, now that I think about it - perhaps just the name `_join` is too narrow? If the table was `item_store_properties` and one of the properties was 'visibility' then it's all good 🤷 

But that leaves the issue of sync and overwriting values. maybe better to split the intentions of that join table.

**Comment by Chris-Petty** [comment]
I think naming to indicate that it's more than a mere join is a good call! Also opens up a clearer alternative... well from a sync perspective anyway...

`item_store_remote_properties`
`item_store_central_properties`

🙃  Idunlikeit. Related thought, permissions and preferences kind of have a very similar structure - possibly should make sure it's a similar pattern (can't emphasise how many times "store groups" have come up as a request). 

<details>
<summary>secret</summary>
Maximum semantic: would be store_item_properties be more natural? Typically I think from a store perspective, not an item perspective.
</details>

**Comment by jmbrunskill** [comment]
@Chris-Petty @mark-prins Should we split out the design of the item <-> store relationship to a new issue and close this one out? 
Keen to understand store groups, is this user's want to say, make an item visible at all the remote sites but not central or something akin to that? Feels like we're discovering some new/future requirements here that need be considered in the new design rather than just copying existing?

**Comment by mark-prins** [comment]
yeah, I think that's sensible. We'll need to involve Andrei in this discussion too, and there's no need to hold up this issue while we ponder.

**Comment by jmbrunskill** [comment]
@mark-prins @clemens-msupply happy with the description on issue #1053 ?

**Comment by clemens-msupply** [comment]
> @mark-prins @clemens-msupply happy with the description on issue #1053 ?

I am not quite familiar with the underlying issue in #1053. Probably best to discus in the office at some point with @Chris-Petty and @andreievg. Think its not urgent?

We can move the remaining item task from this issue into a new issue and close this one...
