### ISSUE TITLE
Unable to start in bootstrap mode using postgres

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/remote-server#1050]
Doing the following when using a postgres database:

- comment out all sync settings in `local.yaml` and `base.yaml`
- restart the server

results in this error:

```
[2022-04-27T00:34:22Z INFO  server] Run DB migrations...
[2022-04-27T00:34:22Z INFO  server] DB migrations succeeded
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DBError { msg: "UNKNOWN", extra: "\"\\\"invalid input value for enum key_type: \\\\\\\"SETTINGS_SYNC_PASSWORD_SHA256\\\\\\\"\\\"\"" }', C:\github\remote-server\server\src/lib.rs:136:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\remote_server.exe` (exit code: 101)
```

Have deleted the pg database and can confirm that the db is empty. Migrations have been run manually, but there is nothing in `key_value_store`

**Comment by clemens-msupply** [comment]
sorry the schema was wrong...

This should have fixed it:
https://github.com/openmsupply/remote-server/pull/1051

**Comment by mark-prins** [comment]
wow, that was quick! thanks - didn't notice that. 
working nicely 😁
