### ISSUE TITLE
Login allowed when central server details incorrect

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/remote-server#1061]
Raised as https://github.com/openmsupply/openmsupply-client/issues/1197 
The steps to recreate are:
- use a new database for the server
- configure central server settings
- ...and sync, but do not log in using the `authToken` endpoint!
- modify the sync settings, so that the remote-server no longer can access the central server
- login using the authToken endpoint

Result: the user is authenticated - however, there is no user account in `[user_account]` and no connection to the central server. How is it possible to authenticate?

The result from the web client pov is that the user is authenticated, but no store available and permission denied errors pop up all over the place.

**Comment by clemens-msupply** [comment]
Proposed solution: on startup if central server can't be reached and there are no users in the DB boot into bootstrap mode.

**Comment by clemens-msupply** [comment]
Pinging the central server without credentials is actually harder than expected, e.g. there is no good endpoint that could be (ab)used for this use case... Could probably figure something out (in a way that might break in the future) but how likely is this scenario? seems unlikely that somebody changes the url in the DB or the central server changes the url while configuring the remote server...

**Comment by mark-prins** [comment]
I think the scenario unlikely - and the ping and revert to bootstrap isn't necessary. 
The main concern was being logged in when the server connection is invalid - that is what appears to be happening and if so, can we just fallback to a default of not authenticated?

**Comment by raviSussol** [comment]
@mark-prins @clemens-msupply I tried to look at the issue and can say that the main issue here is that a user can still login to the store even if that user hasn't got login permission for that store i.e. if there is a record in the `user_account` table but its corresponding record for that store doesn't exist in the `user_store_join` then currently that user is still allowed to be logged in to that store when the sync server is offline.

In the desktop mSupply, the user login basically checks for the user has got its linked `user_store` record in it with `can_login` to `true`. So I think same concept may need here to validate login i.e. when a user logins to the openmsupply then a `user_account` record with its corresponding record in the `user_store_join` table make sure exists. If not found then the login should be stopped. While looking at the issue, I also created a pr for it: #1069 

Let me know if you think a different approach other than that pr is needed to resolve this issue. I'd be happy to know or follow the optimize way.

**Comment by clemens-msupply** [comment]
thanks for looking into it! The login endpoint doesn't take a store_id (on purpose) so you can login regardless if you have access to 0, 1 or more stores. The /me endpoint returns information about which stores the user has access to. As far as I know the UI already checks the /me endpoint but maybe there is an issue when changing stores?

**Comment by mark-prins** [comment]
just to add on to what Clemens has said: while the server does validate the user account, the web app prevents (mostly!) the user from doing anything if the user has no access to any stores. If you login using an account with no stores assign you see this:

![Screen Shot 2022-05-06 at 9 11 47 AM](https://user-images.githubusercontent.com/9192912/167026312-91538be7-ca12-49f2-805c-1db558ede04d.png)

from there, any API requests will give the same error and no data is shown.
We could log the user out as well if you think that's better? maybe give more information? though It's unlikely that users will have no stores - it's not possible to save a user in mSupply with no stores assigned isn't it?

**Comment by andreievg** [comment]
@mark-prins I can't replicate this.

* i removed omsupply-database from root
* cargo run (with central running locally)
* stopped server
* quit local central
* start server and tried authToken endpoint, couldn't log in

**Comment by andreievg** [comment]
@raviSussol in omSupply, form API perspective, there is no concept of 'logging in' to a store, use just logs in and storeId is provided to every query (at this point server decides if user can access the record in the queries, based on provided storeId). There is a `STORE_ACCESS` in [user_permission](https://github.com/openmsupply/remote-server/blob/develop/repository/migrations/postgres/2022-03-25T14-30_create_user_permission_table/up.sql) table for user and store login rights

**Comment by mark-prins** [comment]
@andreievg I can't replicate the exact issue - though there is a different problem 😕 though I think we can ignore it 😄 

When the issue was raised, I just edited the sync settings in the database (to be invalid), and then could login, though due to the invalid settings none of the user permissions would sync, so the user was logged in to the site but couldn't see any stores or do anything.

Now, I edit settings, the user logs in and all the associated data syncs. Even though the settings are invalid. Seems that the connection details are being retained - restarting the server picks up the invalid settings and you can no longer login - either a soft boot or stop / start.

The steps you followed weren't exactly the same as listed in the first comment. The key difference is that I didn't restart the server when I was testing. Not sure if Bijay was restarting or not. This is what I was just doing now to test ( running locally with debug version & sqlite )

- delete sqlite db
- comment out sync settings from yaml files
- start mSupply / 4D
- start web app
- enter sync settings in the bootstrap screen
- wait for sync to finish and the login screen to appear
- open db tool ( dbeaver / DB browser for SQlite etc ) and edit the config settings so that they are incorrect
- login to site through web app
- you are logged in

@bijaySussol : this is your issue, so I won't close. Would you mind retesting with latest `develop` of remote-server and see if it's still a problem for you please?

**Comment by raviSussol** [comment]
@clemens-msupply @mark-prins @andreievg Thanks guys for making clear the login logic for the openmsupply. The only concern was the user could still access without settings store permission for that user. But since this is an intended behavior so no problem with this issue. Also I've already tested on the latest remote-server and openmsupply-client - works as expected. So can be closed this issue now. Looks like you only guys can close the issue - can't close it from mine.

**Comment by mark-prins** [comment]
Thanks Ravi - will have a look at permissions.. I think you should have access to manage issues 🤔
