### ISSUE TITLE
Android requires permissive cors settings -> security issue?

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/remote-server#1070]
remote-server on Android runs on localhost and thus requires permissive cors settings, check if this is a security problem.

**Comment by jmbrunskill** [comment]
@clemens-msupply We could just use the allowed_origin_fn to allow any localhost?

```
              .allowed_origin_fn(|req| {
                  req.headers
                      .get(http::header::ORIGIN)
                      .map(http::HeaderValue::as_bytes)
                      .filter(|b| b.begins_with(b"http://localhost"))
                      .is_some()
              })
```
https://docs.rs/actix-cors/0.4.1/actix_cors/index.html#example

Not sure if that adds much over permissive, I guess it prevents someone accessing a malicious website that tries to connect to localhost with credentials?
If localhost is compromised, I guess all bets are off security wise :)

**Comment by clemens-msupply** [comment]
I still think for proper security we would need a https connection for remote-server <-> UI browser communication (both on the device). This only works by going through the native host when doing this we could also start a mutual authenticated connection. This would allows us to have permissive CORS since we have made sure that only the UI can talk to the server and there are no cross domain requests. To be discussed...
