### ISSUE TITLE
Unable to Print

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/remote-server#1082]
The query `printReport` returns an invalid response when using the demo server.
Am able to print fine when running the server locally though.

<details>

<summary>Query</summary>

```
query printReport($storeId: String!, $dataId: String!, $reportId: String!) {
  printReport(dataId: $dataId, reportId: $reportId, storeId: $storeId) {
    ... on PrintReportNode {
      __typename
      fileId
    }
    ... on PrintReportError {
      __typename
      error {
        ... on FailedToFetchReportData {
          __typename
          description
          errors
        }
        description
      }
    }
  }
}
```

</details>

<details>
<summary>Variables</summary>

```
{
  "dataId": "4dfab70d-1245-4d10-a65a-dc7ff0001a11",
  "reportId": "dummy_report_invoice",
  "storeId": "D77F67339BF8400886D009178F4962E1"
}
```

</details>

**Comment by mark-prins** [comment]
I can see that the PDF is created - could be an issue with CORS 🤷

**Comment by mark-prins** [comment]
More info

```
[2022-05-18T03:51:45Z INFO  headless_chrome::browser::transport::web_socket_connection] dropping websocket connection
thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 123, kind: Uncategorized, message: "The filename, directory name, or volume label syntax is incorrect." }', service\src\static_files.rs:39:43
```

**Comment by jmbrunskill** [comment]
@mark-prins haven't looked too far into it but it looks like filename is made up of...

`format!("{}_{}.pdf", now.to_rfc3339(), report.name`
and
`format!("{}_{}", uuid(), file_name`

my suspicion is that windows doesn't like the rfc3339 date format.
Can you try creating a file called something like "df0096b8-7372-4af5-87ad-fb74f53fdae8_1996-12-19T16:39:57-08:00_REPORTNAME.pdf" in windows and see if it works?

https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names

**Comment by jmbrunskill** [comment]
BTW: I remember for some other projects we created a function to replace any special characters in a filename with something safe like '_'.
Especially since we are using UUID in the final file name, I think we should be safe to implement something like this (assuming the issue is actually a windows filename issue)

**Comment by mark-prins** [comment]
probably is the invalid chars - though the actual file created is `e2a874db-76b4-487f-9ef3-4cbd16ac0a04_Dummy invoice report.pdf` Checking now

**Comment by clemens-msupply** [comment]
Thanks @jmbrunskill good catch!
