### ISSUE TITLE
Existing invisible item does not show when made visible

### ISSUE THREAD

**Issue by ujwalSussol** [openmsupply/remote-server#1088]
Existing invisible item does not show in the Remote_server store even when the item is made visible.

Workflow : 

- Setup a store from an existing mSuppy data file with some items that are invisible.  
- Make sure Remote_server  is ready with the initial data dump.  
- Login using Open-mSupply Client.
- On 4D server view the invisible item and make it visible for the store.
- Error : The existing item does not show despite the sync data being retrieved. 
- Now create a new item.
- See that the new item syncs, but the old existing items do not show. 

You can use this data file and setup the `Store G site` with user `userg`  [password same as the username] to see the above problem.

[combined_server-2022-05-12-T15-59.zip](https://github.com/openmsupply/remote-server/files/8677130/combined_server-2022-05-12-T15-59.zip)

![Store G Site](https://user-images.githubusercontent.com/6764266/168051493-d91c4821-e3e5-492d-bd58-694421ad01b9.png)

**Comment by andreievg** [comment]
@ujwalSussol `On 4D server view the invisible item and make it visible for the store.` is that with master lists (in omSupply item visibility is only controlled by master lists)

**Comment by ujwalSussol** [comment]
> @ujwalSussol `On 4D server view the invisible item and make it visible for the store.` is that with master lists (in omSupply item visibility is only controlled by master lists)

@andreievg  :  ahhh ... OK, no I was controlling the items visibility individually...   I will aim to look at master list next. 

Will close this issue for now.
