### ISSUE TITLE
Programs: Customizable UI

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/remote-server#1094]
In the programs UI design we have custom logo and colours.  Moreover, we have custom UI schema definitions.

How do we store this data? Is this something for a property table? e.g. `store_ui_props`?

**Comment by mark-prins** [comment]
the logo and colours in the f/e are currently just text kept in localStorage (i.e. browser specific). Updated in the Admin section:

<img width="525" alt="Screen Shot 2022-05-16 at 3 28 15 PM" src="https://user-images.githubusercontent.com/9192912/168515027-5286be8a-1632-42ed-85f1-db7c3c20df50.png">
