### ISSUE TITLE
DISCUSSION: authentication and authorization

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/remote-server#144]
Moved to #192.

**Comment by wlthomson** [comment]
@joshxg Made this stub discussion issue for you to put down your thoughts/conclusions. Feel free to update the description with anything I've missed!

**Comment by joshxg** [comment]
Some vague high level thoughts (also my auth knowledge needs work :)):

How do we want to implement authentication, e.g. RESTful endpoint, user_account.username + user_account.password?
- Use REST which can be extended to support `/user`, `/store`, `/sync` and potentially other types, lets just say `/external` for now

What standard/protocol do we want to use? (JWT, oAuth etc?)
- I do like the idea of supporting oAuth but it's probably ott? I wonder what is the cost to switch if we do feel the need to support it at a later date.
- Possibly authenticating a `JWT` with refresh tokens?

How do we want to implement permissions, e.g. prevent stores reading/writing data they do not own?
- `JWT` has some `user_permissions` [Can write CI's] and possibly `user_preferences` [i.e. per user language, CI page show X columns] possibly `session_details` which can have things like the `store_ID` for database access control and filtering `session_ID` (which we could use in telemetry logs?). But this makes the JWT seem very smelly as it has *a lot*.
- There has been thoughts around using row level permissions to manage access control on the database. I am not sure this should be added into the phase1 alpha- I think if the database access is sufficiently abstracted then it shouldn't be too bad to add this in at a later date.

**Comment by wlthomson** [comment]
> How do we want to implement authentication, e.g. RESTful endpoint, user_account.username + user_account.password?
> 
>     Use REST which can be extended to support /user, /store, /sync and potentially other types, lets just say /external for now
> 

Probably missing some info, but don't quite follow!

Let's say the user is at the login screen, and enters his or her credentials and attempts to login. Assuming a RESTful interface, what sort of request would be made to the `remote-server`, and what sort of response would be expected?

**Comment by joshxg** [comment]
Just the standard `{username, password}` in the request and either a JWT in a `Authorization` header or a `Set-Cookie`. I've become a fan of a cookie as it is easy for the frontend to manage, but it is minimal and I don't really mind.

The comments about `/store` and `/sync` are just because in addition to `user`s logging in, there is different auth mechanisms for `sync site`s and `store`s to authenticate with servers.

**Comment by wlthomson** [comment]
Oh, got it! Those additional endpoints confused me, thanks for explanation.

**Comment by wlthomson** [comment]
Moved to #192.
