### ISSUE TITLE
DISCUSSION: mSupply workflows

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/remote-server#145]
Moved to #187.

**Comment by wlthomson** [comment]
@joshxg @mark-prins Feel free to update with any thoughts!

**Comment by joshxg** [comment]
Couple thoughts

- There won't be a need for mutations of system data - items/users. We can have queries for this and assume the sync component will have deposited the required system data (items, users, stores, names) into the database (so.. mock until next year when it's done ;-)) 
- I think for the frontend I have been thinking of starting by focusing on a single workflow: i.e. Supplier Requisition and working through the entire workflow. I believe going deeper into a single workflow (including a small subset of possible plugin implementations) will offer a lot. 
    -  go to supplier requisition list page (query for all SR's [pagination, filtered by time, filtered by status, type etc], related records to the SI's, user permissions check to see if editing is OK)
    - Go to a supplier requisition detail page, query for other related data i.e. lines
    - Possible mutations: Save, Finalise, "Automatic order" (like mobile).
    - Things which can be explored: How does this interact with programs? periods? Variable AMC calculations? Reasons? Is there a validation plugin to ensure every line has a reason?

It does seem like a small amount of things, and it likely is, but we do have mobile/desktop to be able to check to see what mutations/queries are required and surely if the requisition `OnLoad` method being as big as it is, there's a lot more things requisiton queries need to do 🤣

**Comment by wlthomson** [comment]
That sounds good, current focus is probably to go for breadth before depth, e.g. get some basic workflows working before going too deep into any given one. But all of the above sounds consistent with my thought process!

**Comment by wlthomson** [comment]
Update: removed `create X` for any system data.

**Comment by wlthomson** [comment]
Quick activity diagram for the internal order workflow:

![internal_order_workflow](https://user-images.githubusercontent.com/43223637/123199697-7d601880-d503-11eb-98a0-8ddd297f0c6e.jpg)

Feedback appreciated!

**Comment by wlthomson** [comment]
Changed the title of the epic to make a bit more sense (not sure "API workflows" was a very helpful description, sorry!).

**Comment by wlthomson** [comment]
Moved to #187.
