### ISSUE TITLE
DISCUSSION: front-end integration

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/remote-server#146]
Moved to https://github.com/openmsupply/remote-server/discussions/185.

**Comment by wlthomson** [comment]
From what I understand, the suggestion so far is that the front-end should be served by the remote server, i.e. the remote server will expose an HTTP server alongside the RESTful + GraphQL API.

My initial understanding was that each machine would run its own front-end server which would provide some sort of DNS redirection to the `remote-server`, which would then handle all the requests. Is there a reason this design would not work?


Some other questions:

- Will the HTTP server be included in the existing `actix_web::HTTPServer`?
- Will this repo also store all the front-end code?
- If the `remote-server` hosts the HTTP service, how will the users consume it? Is the idea to add a DNS lookup to the local network?

**Comment by joshxg** [comment]
My understanding:

- Each "Remote site" will have a single `remote-server`, where anyone on the LAN will be able to use a browser to connect to it.
- Local DNS: Not sure, maybe?
- It is not a requirement that a user has a `server` installed on their machine to use the web app, they will be able to connect to the omSupply web app on their lan, and there will likely be a server accessible from anywhere on some cloud [Maybe I have a misunderstanding from you here]
- I'm a fan of separating things, so I do think having a separate http server and data server is good. They will have to both be installed on a single machine at a site, so would need a strategy to deal with that so there is no impact on deployment which I am not sure about.

Repo + code
- I am not sure what benefit having a single repo is for these projects, but I am also not sure if there is a downside!

**Comment by adrianwb** [comment]
Just to check if I'm reading between the lines correctly and/or understanding this right:

- each site will have its own "data server", which effectively acts as an interface to Postgres for the local client(s) and/or web app(s)
- only the central server really needs to have its own "HTTP server", which is how the sites sync with each other and where the dashboard is accessed from
- the web app can connect to any site's data server, but only the local one will allow editing (any other site will be read-only)

**Comment by joshxg** [comment]
I think I'm explaining poorly. Sorry.

The idea [afaik] is for the system to be basically identical to our current infrastructure. A client server (Which is serving a data server and web server, serving html) is installed on some site. 
Clients on the LAN can connect to the server through a browser, accessing the web app, which communicate with the client-server on the LAN.

My comment about 'anyone accessing' meant that the 'central server' may expose the port the webserver is served on, which would allow anyone in the country to access that site.

**Comment by mark-prins** [comment]
This doesn't seem particularly helpful: [architecture diagram](https://drive.google.com/file/d/1NwWVVl4jKhrllEKmCoj817If9o5wHtCd/view) - it feels like time for a diagram, and this is the only one I can find.

**Comment by wlthomson** [comment]
@joshxg @mark-prins 

I think the main question (at least wrt. this repo), is how the HTTP server is to be implemented?

Do we plan to write the HTTP server in Rust? If so, will it be a separate process, or another thread in the existing `HttpServer`? I personally think separating the two would be a good idea, but as @joshxg points out, we would need to ensure we had a deployment pipeline that managed both applications. If the plan is for this repo to contain the HTTP server as well as the RESTful/GraphQL resources, should the front-end code be developed in this repo, too?

P.s. is anyone aware of any more comprehensive architecture diagrams? If not, it might be a good idea to meet up and design one (I like the idea of peer-diagramming!).

**Comment by joshxg** [comment]
there is [this](https://drive.google.com/file/d/1NwWVVl4jKhrllEKmCoj817If9o5wHtCd/view) architecture diagram which is all I know of

**Comment by wlthomson** [comment]
Bumping this down to lower priority as probably best revisited when we are a bit further down the line with front-end architecture decisions.

**Comment by wlthomson** [comment]
EDIT: have added a basic c4 container diagram to the description. Feedback appreciated 😃.

**Comment by wlthomson** [comment]
Moved to #185.
