### ISSUE TITLE
Enable GraphiQL

### ISSUE THREAD

**Issue by joshxg** [openmsupply/remote-server#148]
GraphiQL (Like, graphical- so cooool) is super useful with autocompletion, syntax highlighting and showing the schema in the UI. It would be great to have it enabled for testing.

The standard is to have this enabled on `/graphiql`.

If OK, I think this can be a part of the graphql service, adding an additional route and handler. Then, I think added into the graphql service config

**Comment by joshxg** [comment]
@wlthomson what you reckon 😁 ?

**Comment by wlthomson** [comment]
Sounds good to me! `actix_juniper` supports this out-of-the-box with `graphiql_handler` (most examples include it, I initially removed it to keep things simple).

**Comment by wlthomson** [comment]
Fixed by #152.
