### ISSUE TITLE
transact and transact_line mock data methods

### ISSUE THREAD

**Issue by joshxg** [openmsupply/remote-server#155]
The Transact and TransactLine tables have no mock data tables. They should be added :)

**Comment by wlthomson** [comment]
Minor thing for consistency moving forward, `Transact` and `TransactLine` refer to the GraphQL types (`transact` and `transact_line` are the tables, `TransactRow` and `TransactLine` are the sqlx types).

**Comment by wlthomson** [comment]
Fixed by #154.
