### ISSUE TITLE
DISCUSSION: internal orders

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/remote-server#172]
Moved to #189.

**Comment by joshxg** [comment]
Just a little confused with what the diagram is meant to be showing. It is a high level overview of the process, but how is this translating to code or and algorithm? 

For example, is each action in a rectangle suppose to be a query from the browser? Or is it a function invocation?

Also, I am confused about the customer invoice section - I am not sure that is correct. For a customer requisition, we will have an action to create a customer invoice, but nothing to do with finalising.

**Comment by joshxg** [comment]
I've tried to help by doing an example which I think shows some in depth detail of the actions which occur in the customer requisition workflow (incomplete still- a few actions still to add) and where the communication and responsibilities are.

![requisition](https://user-images.githubusercontent.com/35858975/123764435-e3400c00-d918-11eb-83f3-ea94c06bfb30.png)

**Comment by wlthomson** [comment]
I think I haven't really explained well my thinking behind these discussion issues! Since this is the first one, I'll do it here.

Basic idea is to try and start off with a high-level logical diagram of the workflow, i.e. what the user needs to do. I think activity diagrams are good for this, but use-case diagrams probably also would work! Once we get agreement on the basic "what", my thinking was we would then move onto the "how", e.g. sequence diagrams, or container/component diagrams in the [c4 model](https://en.wikipedia.org/wiki/C4_model) (thanks @joshxg for showing me this!). I don't think we will need to go as deep as designing classes in these discussions, that would probably be best left for more specific issues?

Feedback would be appreciated, happy to go with another process if others have suggestions!

**Comment by wlthomson** [comment]
Moved to #189.

**Comment by mark-prins** [comment]
> Moved to #189.

I can't find 189.. is it in this repo?

**Comment by wlthomson** [comment]
Oops, must have forgotten to update this one. I migrated all the discussions to [`org-issues`](https://github.com/openmsupply/org-issues/discussions/8).
