### ISSUE TITLE
webpack federation / micro frontends prototype

### ISSUE THREAD

**Issue by joshxg** [openmsupply/remote-server#184]
Would be good to see web pack and micro frontends in action.

**Comment by wlthomson** [comment]
Looking forward to learning about this 🤓!

Is the thinking to make a PR or any code changes here, or more of a discussion/investigation linking to external examples? Aware that you guys will probably have your own process (might be good for me to follow the same one), but just for short term consistency, would this be better labelled as an epic or a discussion?
