### ISSUE TITLE
Add comments for new rustaceans

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/remote-server#19]
This repo is going to be contributed to by developers who are new to the Rust language. Add comments to document unclear code and to explain concepts unique to the Rust language that may be confusing for newcomers.

**Comment by wlthomson** [comment]
@joshxg Do you have any feedback on any areas you found difficult that could use some additional doccing?

**Comment by joshxg** [comment]
I had this note:

```
When running ` migrate run` add the with DATABASE_URL env var - i.e. `postgres://{postgres username i.e. postgres}@{localhost}/omsupply-database - i.e. DATABASE_URL=postgres://postgres@localhost/omsupply-database sql migrate run
```

**Comment by wlthomson** [comment]
Is the `scripts/init_db.sh` not setting the `DATABASE_URL` env variable for you?

**Comment by wlthomson** [comment]
Seems like the code isn't too hard to understand 👍 . A few people have mentioned that the `README.md` could be improved, which I guess falls under the scope of this issue!
