### ISSUE TITLE
Add tables required for sync

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/remote-server#208]
Need to update schema with tables/fields required by sync.

The main concern is that we cover `change_log` and `sync_queue` data!

EDIT: looks like we are happy with the existing tables below (for now):

| Table              | Fields                                                                     |
|--------------------|----------------------------------------------------------------------------|
| `requisition`      | `id`, `name_id`, `store_id`, `type_of`                                     |
| `requisition_line` | `id`, `requisition_id`, `item_id`, `actual_quantity`, `suggested_quantity` |
| `item`             | `id`, `item_name`, `item_name`, `type_of`                                  |
| `item_line`        | `id`, `item_id`, `store_id`, `batch`, `quantity`                           |
| `transact`         | `id`, `name_id`, `store_id`, `invoice_number`, `type_of`                   |
| `transact_line`    | `id`, `transact_id`, `type_of`, `item_id`, `item_line_id`                  |
| `name`             | `id`, `name`                                                               |
| `store`            | `id`, `name_id`                                                            |

Will also need to add the `sync_out` table, as shown in the [spreadsheet](https://docs.google.com/spreadsheets/d/1TLxjqZ96o67aScQ0abfQ5juzRPr7dZ1Y1vnwdElv3XY/edit#gid=0):

| Field                 | Type          |
|-----------------------|---------------|
| id                    | `uuid`        |
| created_at_timestamp  | `date`        |
| record_id             | `uuid`        |
| store_id              | `uuid`        |
| table_name            | `varchar`     |
| site_id               | `integer`     |
| action                | `sync_action` |

**Comment by craigdrown** [comment]
http://dev.msupply.foundation/docs/sync/sync-queue/ has queue table schema

**Comment by wlthomson** [comment]
> 
> 
> [http://dev.msupply.foundation/docs/sync/sync-queue](http://dev.msupply.foundation/docs/sync/sync-queue/) has proposed queue table schema

More thinking about the tables we want to support syncing, e.g. wrt. the `sync_out` table, what subset of `table_name` do we want to support (or all)?

**Comment by Chris-Petty** [comment]
@craigdrown @wlthomson I want to start a discussion about this. The gist - not all clients consume all tables:

- sync v2/v3, there are conditions that avoid half of system tables for mobile. From then on, I think those tables do get synced to mobile, but mobile just ignores them.
- this remote-server isn't going to have every table out of the gate.

With that said, I think the server should be agnostic to clients. Otherwise you end up with spaghetti code filtering out data which we already have for just 2 clients, desktop and mobile. I think clients should be able to specify what data they are subscribing to. What do ya say?

**Comment by Chris-Petty** [comment]
Note, this mechanism could well be extended to solve the problem of clients upgrading and requiring tables that they didn't require previously. They'd just update what they subscribe to and get a dump of existing data.

**Comment by wlthomson** [comment]
>  I think clients should be able to specify what data they are subscribing to. What do ya say?

I think this is a v. good idea, and likely has some relevance to plugins also. 

I can see it working quite well for the read-only `change_log`, but might be a bit tricker re. `sync_queue`? E.g. would have to update acknowledgement so server knows what records to clear? Could the queue grow and grow with lots of records which the consumer never pulls?

**Comment by wlthomson** [comment]
Bringing the discussion back towards tables, do we have some idea of the "core" tables and fields that we need?

I've updated the description with a table stub that we can maybe expand out?

**Comment by wlthomson** [comment]
Have updated entry for `requisition` based on the [workflow diagram](https://drive.google.com/file/d/1XtC8hHoOmKhznTSYEyARZ_WXWqm8WeEe/view?usp=sharing) and updated the [spreadsheet](https://docs.google.com/spreadsheets/d/1TLxjqZ96o67aScQ0abfQ5juzRPr7dZ1Y1vnwdElv3XY/edit?usp=sharing).
