### ISSUE TITLE
Add example filtering using Diesel

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/remote-server#262]
Add example of conditional query building based on filters using Diesel ORM.

**Comment by andreievg** [comment]
Can these include both database please (as can they be common for both), I wasn't sure what this meant: http://docs.diesel.rs/diesel/query_dsl/trait.QueryDsl.html#method.into_boxed
`The backend must be specified as part of this. It is not possible to box a query and have it be useable on multiple backends.` does it mean we have to double up on filter query for each database ?

**Comment by wlthomson** [comment]
Closing as outdated.
