### ISSUE TITLE
[SYNC] - Central queue

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#278]
MW parent job: `[OMSBES] omSupply Back End - SYNC`

### Description

Intermediary sync queue, to store incoming sync record before they are integrated.

### Table

Common columns to be fields (i.e. record_id, record_type), payload to be a text (not JSON), since it will be de-serialised with serde for simple translations

### Scope

<ins>Includes</ins>
* Add table
* Able to insert many record
* Able to get one records
* Able to clear queue

<ins>Excludes</ins>
* GraphQL mutation for getting/setting settings

### Tasks

- [ ] Break down tasks into digestible (by reviewer) units.
- [ ] MW job added

**Comment by wlthomson** [comment]
I think I may have duplicated this with #296. Will delete that and rename the branch.
