### ISSUE TITLE
[SYNC] - Pull Central

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#279]
MW parent job: `[OMSBES] omSupply Back End - SYNC`

### Description

I think this is mainly implemented, just need to store in intermediary central sync queue

### Table

Need to store central cursor

### Scope

<ins>Includes</ins>
* Able to request and pull X number of records of central data
* Able to store those records
* Able to increment cursor queue
* Able to result in "all done" (all records were pulled)

<ins>Excludes</ins>
* Validation of incoming sync record shape/type

### Tasks

- [ ] Break down tasks into digestible (by reviewer) units.
- [ ] MW job added

**Comment by wlthomson** [comment]
I'm gonna make a start on this by implementing the HTTP logic for pulling from the central queue (currently only pulling from remote is implemented).

**Comment by wlthomson** [comment]
Next step: add logic for saving successfully pulled records into central sync buffer (#331).

**Comment by wlthomson** [comment]
Next step: add table and logic for persisting sync cursor (#336).

**Comment by wlthomson** [comment]
Closing as all tasks completed!
