### ISSUE TITLE
[SYNC] - Simple Translation Full - M1

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#281]
# Description

Add enough table and simple translations for them to satisfy M1 spec

### Scope

<ins>Includes </ins>
* item - (code)
* name - (code, is_customer, is_supplier)
* store - (code)
* ~~item_store_join~~
* ~~name_store_join~~ (would be part of remote sync, one way from central only)
* master_list_join
* master_list
* master_list_line

`list to be revised based on front end specs`

<ins>Excludes</ins>
* Api
* Complex translation in name_store_join

### Tasks

- [ ] Break down tasks into digestible (by reviewer) units.
- [ ] MW job added

**Comment by clemens-msupply** [comment]
Is it guaranteed that the sync records come in in order from the central server? e.g. if a store refers to a name is it guaranteed that this name comes before the store in the received sync list?

**Comment by andreievg** [comment]
No guarantee:

https://github.com/openmsupply/org-issues/discussions/33

Under 'Atomic Batched Sync'. Two ways to solve it:

* Transaction with defferrred fk check (which only work in postgres, there is an alternative in sqlite, but it's not good: https://github.com/openmsupply/org-issues/discussions/33#discussioncomment-1232353
* Order records in transaction in order of reference
     * Need to have a list of reference priority (which i what i was suggesting for what we call 'migrations' (database schma initilisation scripts)
     * This can either be hard coded, or we can calculate it (in the snapshot branch i've sent there is this: `calculate_table_order` method that does it, and something similar in mFlow project, from this [sql](https://github.com/openmsupply/application-manager-server/blob/develop/database/buildSchema/47_database_info.sql), generates type object in this [shape](https://github.com/openmsupply/application-manager-server/blob/a147d9bc656cfce02b64b411771d0cfdca16718f/src/components/exportAndImport/types.ts#L1-L24), and then [order is by reference](https://github.com/openmsupply/application-manager-server/blob/a147d9bc656cfce02b64b411771d0cfdca16718f/src/components/exportAndImport/getDatabaseInfo.ts#L112-L127)

Keen to discuss this today in sprint meeting.

Btw i didnt' quite spec this out properly because I wasn't aware that sqlite doesn't have the same deferred fk check functionality in transacitons.

I think we would need to query buffer queue in batches of table_name (from highest to lowest)

**Comment by andreievg** [comment]
@clemens-msupply i think this one was closed by accident ? It should be the mechanism one ? (we can look over it at sprint meeting)

**Comment by clemens-msupply** [comment]
yes, sorry

**Comment by andreievg** [comment]
@clemens-msupply I've just update the main description section

**Comment by andreievg** [comment]
and updated again (removed name_store_join)
