### ISSUE TITLE
[API] - Invoices

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#307]
MW parent job: `[OMSBEA] omSupply Back End - API`

### Description

Invoices query (as per docs)

`note` to be done after `invoice`, `sorting`, `filtering` and `pagination`

### Scope

<ins>Includes</ins>
* Add query for all fields in invoices
* Add filtering sorting and pagination from existing mechanisms

<ins>Excludes</ins>
* Related table filtering
* Multi sort

### Tasks

- [ ] Break down tasks into digestible (by reviewer) units.
- [ ] MW job added

**Comment by clemens-msupply** [comment]
Filtering and sorting still missing...
