### ISSUE TITLE
[API] - Customer Invoice Insert/Update Mutations

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#348]
MW parent job: `[OMSBEA] omSupply Back End - API`

### Description

Mutations for insert and update of customer invoice (excluding lines)

### Scope

<ins>Includes</ins>
* Invoice table changes
* Customer Invoice Insert Mutation
* Customer Invoice Update Mutation
* When status changes update dates
* Validations
  * Name is Customer and is Provided
  * For insert, ID doesn't already exist
  * For update, ID exists
  * Can't change status to draft once confirmed
  * Cannot edit at all once finalised

<ins>Excludes</ins>
* Customer Invoice lines

<ins>Blockers</ins>
* How to do business logic ?
* Not a blocked for dev but for completion -> Invoice API

### Tasks

- [ ] Break down tasks into digestible (by reviewer) units.
- [x] #391.
- [ ] #399.

**Comment by andreievg** [comment]
@wlthomson, this seems like a higher priority this week than the API tests.

In our conversation last week, it looks like we are changing to a more granular mutations. 

* `updateCustomerInvoice`
* `insertCustomerInvoice`
* `deleteCustomerInvoice` 
* `insertCustomerInvoiceLine` 
* `updateCustomerInvoiceLine`
* `deleteCustomerInvoiceLine`

From recent conversations, it seems `upsertCustomerInvoiceLine` is a better shape for front end (can we think of adding this one after base mutations are done, as it would be using logic from insert and update (and a bit of extra validation)

Previous spec (in docs) is in the branch: https://github.com/openmsupply/remote-server/pull/335
Error interfaces and shapes: https://github.com/openmsupply/remote-server/pull/359, and see the bottom of this comment
Can follow this chart for various in CI: [diagram](https://app.diagrams.net/?state=%7B%22ids%22:%5B%221koYWeiC68ajHBXBExj_U8GX41Gor_Q8-%22%5D,%22action%22:%22open%22,%22userId%22:%22113763083123834102221%22,%22resourceKeys%22:%7B%7D%7D)
There is no real need for multiple errors, so I think the general result can be:

```graphql
union UpdateCustomerInvoiceResult = Invoice | UpdateCustomerInvoiceError

type UpdateCustomerInvoiceError {
    id: String!
    error: UpdateCustomerInvoiceErrorInterface
}

interface UpdateCustomerInvoiceErrorInterface {
  description: String!
}

type OtherPartyNotACustomer = implements UpdateCustomerInvoiceError {
     description: String!
     other_party: NameNode
}
# etc..
```

Would recommend breaking this and https://github.com/openmsupply/remote-server/issues/350, into parts:
* empty root queries and shapes and types of errors for all mutations (this can be validated by front end while working on actual implementation)
* Invoice update and insert
* Invoice line insert
* Invoice line update

`Some extra logic`

When invoice changes to confirmed need to update total_number_of_packs on stock lines. Similar if invoice is confirmed we would need to update total_number_of_packs on stock_line.

Let me know if it's easier to chat about this.

I'll do the same for supplier invoice, and we can align both implementations after version is released for front end to integrate.

You'll see below that we go from enum to simple object to interface to enum (async graphl doesn't allow you to use interface inside an enum), so have to use intermediary errors type with errors key (btw no need to errors array, can just be single error now, I think that simplifies it a bit), and of course no reason for lines anymore

https://github.com/openmsupply/remote-server/blob/472e01ef21111c9694f77af187afe338c3dc983d/src/server/service/graphql/schema/mutations/mod.rs#L24-L28

https://github.com/openmsupply/remote-server/blob/472e01ef21111c9694f77af187afe338c3dc983d/src/server/service/graphql/schema/mutations/supplier_invoice/insert.rs#L17-L20

`ApiErrors` =

https://github.com/openmsupply/remote-server/blob/472e01ef21111c9694f77af187afe338c3dc983d/src/server/service/graphql/schema/mutations/supplier_invoice/mod.rs#L38-L42

https://github.com/openmsupply/remote-server/blob/472e01ef21111c9694f77af187afe338c3dc983d/src/server/service/graphql/schema/mutations/supplier_invoice/mod.rs#L53-L57

**Comment by wlthomson** [comment]
@andreievg Thanks! I'll get moving on this now 👍 .

**Comment by wlthomson** [comment]
@andreievg A couple of questions:

- Currently we have `InvoiceNode` as the gql object representing an invoice. The docs specify returning gql type `Invoice`. Should I treat these as the same thing for now (i.e. should `InsertCustomerInvoice` and `UpdateCustomerInvoice` return `InvoiceNode`)?
- Are the docs in #333 up-to-date in terms of the shape of the mutations (except for the lines)? Is that the branch you intended to link above (instead of #335)?

**Comment by andreievg** [comment]
Sorry, yeah docs need to be updated, InvoiceNode seems good to me.

**Comment by andreievg** [comment]
> Are the docs in #286 customer invoice mutation doc #333 up-to-date in terms of the shape of the mutations (except for the lines)? Is that the branch you intended to link above (instead of #286 update tranlsation in query api docs #335)?

`286-update-tranlsation-in-query-api-docs` <- this should be the branch that consolidates all doc changes (minus new way to handle errors and minus breaking down the mutations)

yeah, the shape should be accurate (there is shape there also for line insert and update). Lines would also need to have invoice_id as required field
