### ISSUE TITLE
Filter API option for is_customer and is_supplier -> enum?

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/remote-server#390]
Since they are mutually exclusive should we just use an enum as input parameter?

**Comment by andreievg** [comment]
hmm, i wonder if there is ever going to be a case where we want to select both, can't think of one, enum does sounds like a better way to do it. what would it be called ?

**Comment by andreievg** [comment]
I think it's a good idea, but I have a feeling it is in very low priority basket, and might not be done and just sit in issue back log.

also adding typed equal_to filters requires a bit more code and translations between layers, maybe it's cleaner as bool
