### ISSUE TITLE
Migrate database on server startup

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/remote-server#478]
Add functionality to run diesel migration on server startup.

**Comment by mark-prins** [comment]
I'm not sure of terminology; migration is working with a blank database isn't it? What I'd really like to see is an update of an existing installation - on the demo server we have data, and every time I update the API I have to delete the database, migrate, and recreate data. Could an update be part of this task? separate issue?

**Comment by andreievg** [comment]
Clemens implemented: https://github.com/openmsupply/remote-server/pull/775.

But this still relies on us adding migrations correctly, with remote sync it should be reasonable easy to upgrade via drop dp, create db, starts server (which would sync all central and remote data).

When app is in the wild, we will start doing proper migrations (it's so much simpler to treat database init as single sql statement for each table, especially in sqlite and especially when lots of changes are still being made to existing tables). 

Very sorry for the amount of work this has cause, but remote sync is on it's way : D
