### ISSUE TITLE
Session Handling

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#506]
Placeholder issue, to be broken down further

**Comment by clemens-msupply** [comment]
Outline (DRAFT):

Step1 (register, login, authentication):
1) endpoint to create/register a new user (without auth, i.e. everybody can register for now)
    - submit username / password
    - store username / hash(password) in user table
2) generate server secret on startup if not already exist (maybe use rowdy for all jwt details...)
3) endpoint to login with username/password which returns a jwt
4) add validation helper to validate graphql requests

Step 3 (logout)
1) in memory cache of current token(s)
2) endpoint to logout -> invalidates all active tokens for a user
3) add check in validation helper that token is active

Step 2 (refresh token)
1) return refresh token along with the auth token when doing a login
2) store refresh token in HttpCookie (and SameSite policy) (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite)
3) add refresh token endpoint (or reuse existing login endpoint) which returns new auth token and new refresh token

The HttpCookie part is mostly based on the following blog, which makes sense to me: https://hasura.io/blog/best-practices-of-using-jwt-with-graphql/

Step 3 (permissions)
...
