### ISSUE TITLE
GraphQL API change requests v1

### ISSUE THREAD

**Issue by joshxg** [openmsupply/remote-server#512]
Have integrated the API and it's amazing. There are a couple of low priority issues as of right now and some more points which could be discussed.

**Add Field**
- `[invoice]hold` - boolean. Should prevent (all) status changes. Would be sufficient to just be a boolean and introduce logic for status change prevention at some other point (we prevent on in the ui already, the error would just be for multiple users, really). 
  - [x] https://github.com/openmsupply/remote-server/issues/526
- UPDATE 26/10 : `[invoiceLine]location` - string. We've been asked to display location of the lines within an outbound shipment. I'd expect this to be `[Location]description` using `[trans_line]location_ID` ** 
   - [x] https://github.com/openmsupply/remote-server/issues/542
   - [x] https://github.com/openmsupply/remote-server/issues/543
   - [x] https://github.com/openmsupply/remote-server/issues/544
- UPDATE 26/10: `[item]unit` - string. Also been asked to show unit for items
    - [x] https://github.com/openmsupply/remote-server/issues/534
    - [x] https://github.com/openmsupply/remote-server/issues/535
- UPDATE 28/10: `[invoice]pricing.tax` : I had to go looking for this in mSupply - there's a default set in prefs and then more prefs to allow for editing this in the UI. Currently have no UI for this for omSupply, but should just need to show the value. Since we likely need prefs (or properties?) for this, maybe it can wait?
- UPDATE 29/10: `[InvoiceLine]onHold` listed already in the list of field changes as M2; is now being used in the UI
   - [x] https://github.com/openmsupply/remote-server/issues/538
- UPDATE 30/10: `[InvoiceLineNode]note` : Need in the invoice line [Note that this is the [StockLine]note]
  - [x] https://github.com/openmsupply/remote-server/issues/540

**Add feature**
- use `invoiceNumber` to get a specific `invoice` [use case: We want nice URLs for links). We are using `ids` at the moment which works fine but looks ugly - low priority.
  - [x] https://github.com/openmsupply/remote-server/issues/547
- UPDATE 26/10: Added `InvoiceSortFieldInput` values: `otherPartyName`, `pricing.totalAfterTax` (🤔 total? [cary over](https://github.com/openmsupply/remote-server/issues/551)), `comment`  , invoice number
  - [x] https://github.com/openmsupply/remote-server/issues/550
- UPDATE 26/10: Add nested `otherParty` in `type InvoiceNode`
  - [x] https://github.com/openmsupply/remote-server/issues/545
- UPDATE 28/10: Add an `other charges` feature [This is in current mSupply under the invoice]. Don't have UI for this but adding a way to add an other charge through a mutation. Actually just checked the field changes and this looks like we're using trans lines for this, so.. implementing that?
- UPDATE 2/11: Add a placeholder line input to .. add [placeholder lines](https://github.com/openmsupply/remote-server/issues/531)
- UPDATE 2/11: Add a mutation `assignPlaceholders` which we can use to assign [placeholder lines](https://github.com/openmsupply/remote-server/issues/531) in the invoice
- UPDATE 3/11: Please sort alphabetically ( ignore case )
  - [x] https://github.com/openmsupply/remote-server/issues/555

*Nit/Discuss*:
- ~~I have found myself mistyping `XDatetime` with `xDateTime` many times. I don't know what's right but it's an annoyance for me 🤣 ~~
- Customer invoices are now an `Outbound Shipment` - I think it would be better if we use this name, personally (SI: `Inbound Shipment`).
  - [x] https://github.com/openmsupply/remote-server/issues/517
- The statuses for CI/SI are: `draft`, `allocated`, `picked`, `shipped`, `delivered` from what I understand as per this document: 
  - [ ] (don't think it will be done in M2) https://github.com/openmsupply/remote-server/issues/530
- The sort keys are SHOUTING which I do understand, your enums are a certain way, but I'd prefer to just use the field keys as camelCase ;-)
  - [x] https://github.com/openmsupply/remote-server/issues/549
- `[invoice]color` - hex string? There has also been a mention that this should be integrated with transaction categories, which is why I have put it down here rather than a for sure added field.
  - [x] https://github.com/openmsupply/remote-server/issues/565

These were the notes that I took at the time, there might be more.

**Comment by joshxg** [comment]
Have added a placeholder line input to the features and also we're thinking an `assignPlaceholders` mutation?

**Comment by andreievg** [comment]
I've made an issue for unallocated line discussion: https://github.com/openmsupply/remote-server/issues/531

**Comment by andreievg** [comment]
> UPDATE 30/10: [InvoiceLineNode]note : Need in the invoice line [Note that this is the [StockLine]note]

I haven't been able to figure out how to actually edit line note in CI ui in mSupply, but when I change that trans_line in record browser, it appears in note field, so would assume it's coming from invoice_line.note.

**Comment by joshxg** [comment]
How I think it works: When a trans line is created, the item line note is copied over. It's a note for the batch, rather than the specific trans line and copied over to the trans line, I think, for historic reasons.

You then can edit item line notes through Item > Batches (I think)

This is confusing to me and I can see that a trans line comment might be useful, separately from the item line note. However, that's not currently in mSupply. The current requirement I have is to show the same note that's in mSupply

**Comment by mark-prins** [comment]
ah. I thought it might be the item_line note; was thinking that we'd bring that through as a read-only note on the stock line. It would appear not

![Screen Shot 2021-11-04 at 12 58 22 PM](https://user-images.githubusercontent.com/9192912/140235474-f86d4b51-36dd-41f6-83e5-a062358b19cb.png)

Looks like it is used when there's a linked requisition, so that particular note could just be si only?

```
		$r_pack_size:=$oLinkedRequisitionLine.requestedPackSize[0]
		$bIsPackSizeFixed:=True

		If ($t_note="")
			$t_note:="Requested pack size "+String($r_pack_size)  // add note
		End if 
```

**Comment by andreievg** [comment]
Thanks you both: https://github.com/openmsupply/remote-server/issues/540

**Comment by andreievg** [comment]
Looks like all of the issues were addressed
