### ISSUE TITLE
Invoice status logs

### ISSUE THREAD

**Issue by joshxg** [openmsupply/remote-server#516]
👋 

This maybe better off as a discussion, unsure :)

We have this feature suggested:

![image](https://user-images.githubusercontent.com/35858975/138978202-4272d35c-8e67-4a8d-b697-c7805a0edb8f.png)

Which is a timestamp of when an invoice changed status. 

- Technically, (afaik) this feature is in mSupply currently (via the Log tab, which we also have). 
- I have recommended that we push the `[log]` table to later, however, I that could be one possible implementation of this feature
- Other options include using the various dates on the invoice itself (bit hacky) or having a specific `[invoice_status_log]` table and I am sure there are others.

I make this issue now to determine if there is some implementation that means we can implement this easily soon (I suspect that it will take a bit of time, given there is a discussion on improving logging here: https://github.com/sussol/msupply/discussions/9527 - and I would suspect that would be the desired implementation for this, also)

**Comment by andreievg** [comment]
https://github.com/openmsupply/remote-server/issues/530
