### ISSUE TITLE
Unallocated line

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#531]
- [x] https://github.com/openmsupply/remote-server/issues/664
- [x] https://github.com/openmsupply/remote-server/issues/665
- [x] https://github.com/openmsupply/remote-server/issues/666
- [x] https://github.com/openmsupply/remote-server/issues/669
- [x] https://github.com/openmsupply/remote-server/issues/667
- [x] https://github.com/openmsupply/remote-server/issues/681

As per: https://github.com/openmsupply/remote-server/issues/512#issuecomment-956963908

> UPDATE 2/11: Add a placeholder line input to .. add placeholder lines

> UPDATE 2/11: Add a mutation assignPlaceholders which we can use to assign placeholder lines in the invoice

> Have added a placeholder line input to the features and also we're thinking an assignPlaceholders mutation?

@joshxg @mark-prins, what would be the exact examples of these mutations. And do we have screenshots of how this looks ?

**Comment by andreievg** [comment]
Technically speaking we can just allow for stock_line_id to be optional in existing queries, and that would be considered an unallocated lined (would need an extra check to make sure only one unallocated line exists for an item in the invoice).

But this might be problematic in save button workflow. i.e.

* unallocated line (line_1) is created for item A with number_of_packs = 20
* unallocated line is fulfilled from two stock lines, stock_line_A (pack_size 2, number_of_packs, 5), stock_line_B (pack_size 5, number_of_packs 2), this creates two extra lines (line_2, line_3)
* At this stage placeholder line should really be deleted since it's been fully fulfilled (or if it's want' fully fulfilled it should be reduced by the quantity that's been issued)
* I have no idea what caching mechanism you are using, but would assume you'll have to think carefully about a scenario where 'save' button is pressed and single batch mutation happens, but line_3 or line_2 cannot be reduced by the specified amount, so placeholder line would need to be re-adjusted (re-created if it was meant to be deleted, or re-adjusted to a pre issue quantity)

**Comment by mark-prins** [comment]
> And do we have screenshots of how this looks ?

you mean on the site? Not sure if this helps..
![Screen Shot 2021-11-04 at 11 49 27 AM](https://user-images.githubusercontent.com/9192912/140221001-de01d0dd-5b4d-44d9-b71b-78849f448488.png)

Currently in desktop a stock_line_id is allocated, though I think a null is more informative than a random GUID `[trans_line]item_line_ID:=UUID_generate` 🤷 

Another option would be to create a 'placeholder' item which can have a quantity allocated.

Haven't worked up the error states yet - was hoping to get the API integrated first to see what would happen. I would expect that we would redisplay the result of the mutation and a message explaining what went wrong - in which case the user can increase the quantity of the placeholder, if they want.

Another related question is how to handle service items, which I see also have a dummy item_line_ID allocated:

<img width="1011" alt="Screen Shot 2021-11-04 at 12 12 02 PM" src="https://user-images.githubusercontent.com/9192912/140231354-d39c2b4a-036b-40fa-bcae-7e933da79f3a.png">

Should those also send a null value for the stock_line_id?

**Comment by joshxg** [comment]
Don't have an exact shape of the mutation right now, some initial thoughts on what it could do:

- Take an item ID or placeholder line ID and distributes for that item (assumes invoice in db is all up to date)
- Take all the trans lines for an item, saves them and assigns placeholders

placeholders phase 2, anyone? 😃

**Comment by andreievg** [comment]
We can do a simple mutation for unallocated line, with quantity and item. And add it to batched mutations. I can think of a scenario where this might be difficult for f/e:

Item A starts with unallocated line of 20 quantity
Two stock lines are used to full fill it, say 10 and 10.

So batched mutations would be something like this:

insert unallocated line: 20
insert invoice line A: 10, insert invoice line B: 10
delete unallocated line

if invoice line b can't be reduced by 10, an error will be returned (and invoice line A inserted), now in database unallocated line is at 20, but it should really be 10. So an update for unallocated line would need to be created ? 

I am not sure how f/e keeps track of what needs to be mutated, but if it's by operation, then the batched mutation will have two updates for unallocated line before it's deletion, one of them would need to be removed or changed in invoice line B is changed from 10.

Also if use decided to abandon the invoice for now, unallocated line would not match with quantity that was already full filled.

I like the idea that Clemens suggested with target quantity, so unallocated line has target quantity and remaining unallocated quantity can be calculated and exposed with api.

Although i don't really like the idea of removing unallocated line, i think it would need to be done (when it's fully allocated), since invoice status allocated is only allowed when all unallocated lines are unallocated, and if unallocated line is kept after status change and after that invoice lines that full full that unallocated line are reduced, invoice will once again becomes unallocated.

Anyway proposal is to create unallocated line mutation with target quantity, and unallocated line node would have target quantity, allocated and unallocated quantity. Once fully allocated, unallocated line is deleted.

**Comment by joshxg** [comment]
![image](https://user-images.githubusercontent.com/35858975/145287266-ded3257b-bd48-477b-84ad-8e090a089bc5.png)
