### ISSUE TITLE
Update docs for windows users

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/remote-server#561]
Another item raised earlier when I had trouble with windows didn't make it into the docs, and I've now had the same problem because I forgot about the issue.

When running the diesel migration, you cannot use single quotes in the parameters, when running on windows.

It would also be good to warn users not to try and use the `DATABASE_URL` env var... as this will crash the server

**Comment by clemens-msupply** [comment]
Does
`diesel migration run --database-url="postgres://postgres:password@localhost:5432/omsupply-database" --migration-dir migrations/postgres`
works? i.e, with double quotes?

I didn't know about DATABASE_URL. In what context are you using it? what was the crash?

**Comment by mark-prins** [comment]
yep! double quotes works fine, as does the second syntax used for the migration dir: no quotes at all. 
These were all fine: 
```
diesel migration run --database-url="test.sqlite" --migration-dir migrations/sqlite
diesel migration run --database-url "test.sqlite" --migration-dir migrations/sqlite
diesel migration run --database-url test.sqlite --migration-dir migrations/sqlite
```
Just bad luck that the docs had the one option that windows disliked.
