### ISSUE TITLE
F/E branch changes questions

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#567]
Based on this: https://github.com/openmsupply/remote-server/compare/front-end-fun, simpler version: https://github.com/openmsupply/remote-server/compare/ae5d530435c6dbb94a45c04d80ee9fc97af3c21f...front-end-fun

### item_unit

item_unit was added to invoiceLineNode. Is it ok if this is exposed via invoiceLine.item ? Since it doesn't quite fit with the item_name and item_code that's exposed in invoiceLine (both are those are de-normalised from item to invoice_line for historic purposes). 

Also due to invoice_line database/diesel query logic, we would have to specify double joined diesel boxed query type  (which is quite a bit of complexity for one extra field)

I think location is easier since it's just one left table join

### InvoicePricing

subtotal -> what is this one ? 

Would this work ? :

InvoicePricing {
   total_after_tax,
   total_before_tax,
   total_tax_percentage,
   service_before_tax, // this is the total of all invoice_lines of service type (that have items of type service and no stock lines), item name can be editable in invoice (or maybe some items have them as non editable, and set), likewise with sell/cost price of the line
   service_after_tax,
   service_tax_percentage,
   stock_before_tax, // this is the total of all invoice_lines of stock type, with pricing information coming from stock line (i think tax can be variable for each invoice line)
   stock_after_tax,
   stock_tax_percentage,
}

btw in omSupply invoice lines store cost/price, tax and total after tax (and totals are calculated on the go)

### Other Invoice Fields

Should we go with more description `created_datetime` for `draft_datetime` ? (currentlly it's entry_datetime)

`entered_by_name` -> i think user_ID in mSupply is 'lastModifiedBy'.  So not sure about the logic for this. Would be great to have an audit trail of all of the edits, by user, but that would require further discussion and more granular way to expose the log in gql schema. For now, can we have 'lastModifiedBy' -> userNode ? 

`inbound_shipment_number`, what is this one ?

`purchase_order_number`, `goods_receipt_number`, would these be just external system reference fields (should they be enterable strings) ? Or would they be for existing mSupply invoice records ? Or are we doing PO's etc in V1 omSupply ?

@mark-prins @joshxg, some questions

**Comment by mark-prins** [comment]
For a [simpler comparison](https://github.com/openmsupply/remote-server/compare/ae5d530435c6dbb94a45c04d80ee9fc97af3c21f...front-end-fun) I've used the version prior to develop moving around!

I should say that the wise comments here are Josh's, though I'm happy to document etc.

### Item unit
 ⁃ Obviously `itemUnit` is easier for us, but there’s not some constraint that requires us to flatten the shape Your call whether that’s too hard.
- Same with the location - flat is easier, if it has to be a `location` object then we can change it up

### InvoicePricing 

 ⁃ Subtotal is what you have as `totalBeforeTax`. Shows as `Subtotal` on invoices in desktop and is the `[transact]subtotal` field ( the consistency of total_before_tax and total_after_tax is clearer though! )
 ⁃ totalTaxPercentage: maybe just tax percentage? Not sure what a total percentage would refer to? 
 ⁃ The rest seem fine

> btw in omSupply invoice lines store cost/price, tax and total after tax (and totals are calculated on the go)
Oh. Then we need the `[InvoiceLineNode]taxPercentage` , then. And also where is the items default tax percentage coming from? Item? Or more likely, Item store join (for reference, currently in mSupply I believe it’s a preference. Another preference to allow editing of tax)? Can we have `[ItemNode]defaultTaxPercentage`, or `[ItemNode]itemStoreJoin` (Or `[ItemNode]storeSettings` :thinking)

desktop has only `[transact]tax` that I can see - a single value for the whole invoice. Is that getting mapped across? How does that work with the invoice lines?

### Other invoice fields

> Should we go with more description created_datetime for draft_datetime ? (currentlly it's entry_datetime)

whatever
Mark is regretting updating the datetime fields and will undo all of those. ( though `InvoiceSortFieldInput` did have `finalisedDateTime` which was strangely inconsistent, so happy to update that one :) )

> enteredByName

I suppose you’re talking about an implementation where the enteredByName comes from the log table (actually, the ‘log’ tab of an invoice was meant to be in phase1 - I’ve pushed it back cause I figured it would take too much time). I assumed user_id was the entered by name as that is what it is in mobile, oops.

What if we have `enteredByName` which you can just make equal to the `lastModifiedBy`, for now, but eventually make it really who created the invoice? (If this needs to be a user node, that’s fine, again up to you if the flattening is too difficult).

> numbers

These are the invoice numbers of the related documents, so we can display them and potentially show some details, or link to them where appropriate. Not enterable

not doing POs Goods Receipt and all that in v1 I don't think. This is to just display in the details panel of invoices

**Comment by andreievg** [comment]
> For a simpler comparison I've used the version prior to develop moving around!

thanks added to top comment

> desktop has only [transact]tax that I can see - a single value for the whole invoice. Is that getting mapped across? How does that work with the invoice lines?

There is a partial description in this [doc](https://docs.google.com/document/d/1yiPVBWJDQ5QtUm4-5BQwbaTJQCiVSRYT1RHUk7HIGRQ/edit), that description is not that great, I made a seperate issue: https://github.com/openmsupply/remote-server/issues/569

> Actually Mark is regretting updating the datetime fields and will undo all of those. 

A pr is coming for invoice statuses, in which suggested field in this issue will be used: https://github.com/openmsupply/remote-server/issues/530, i think the only difference there is `draftDatetime`, which is `enteredDatetime` there and `createdDatetime` suggested here lol, so idk.

> ( though InvoiceSortFieldInput did have finalisedDateTime which was strangely inconsistent, so happy to update that one :) )

- [ ] Oops will amend

> What if we have enteredByName which you can just make equal to the lastModifiedBy, for now, but eventually make it really who created the invoice? (If this needs to be a user node, that’s fine, again up to you if the flattening is too difficult).

Oki

> not doing POs Goods Receipt and all that in v1 I don't think. This is to just display in the details panel of invoices

Sweet, just fyi we can't hard code values for things in actual realease, and if PO and goods receipts are not implemented, theses values will always be null (unless it's for existing mSupply sites that have migrated to omSupply)

> These are the invoice numbers of the related documents, so we can display them and potentially show some details, or link to them where appropriate. Not enterable

So what would `inbound_shipment_number` be related to ? I can't think of any invoice that has to be linked to inbound_shipment_number (can potentially see `inbound_shipment` being linked to `outbound_shipment_number` for transfers, but no idea about `inbound_shipment_number`)

**Comment by mark-prins** [comment]
I've given up on the front-end branch and will change the demo server back to using `develop`
As part of that we're removing all the functionality from the front-end which requires extra fields in the API and will move on to newer functional areas instead.

**Comment by mark-prins** [comment]
> So what would inbound_shipment_number be related to ?

Might have snuck in from a design mock up, I can't find the specific requirement now. Requisition should be on the list though, and I can't see that above. Could I swap req for inbound_shipment_number?

**Comment by andreievg** [comment]
I think this is all done, as we've made quite a few requested changes since then for the areas mentioned in this issue
