### ISSUE TITLE
Invoice pricing

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#569]
## Schema

`invoice_line`.**cost_price_per_pack** and `invoice_line`.**sell_price_per_pack** 

For `Inbound` shipment, both are enterable and are transferred to stock_line.
For `Outbound` shipment, both come from stock_line

**Q1** -> for `Outbound` shipment, should this also be enterable ?

`invoice_line`.**total_before_tax** 

Either `invoice_line`.**cost_price_per_pack** or `invoice_line`.**sell_price_per_pack** (depending on `Inbound` or `Outbound `shipment) multiplied by `invoice_line`.**number_of_packs**

`invoice_line`.**total_after_tax** 

Currently it's just `invoice_line`.**total_before_tax**. In omSupply we would store tax on each invoice_line rather than on invoice itself. 

**Q2** -> How to handle tax amount, should it be enterable ?

**invoice**

totals are deduced from invoice_lines

## Api

invoice has InvoicePricingNode under `pricing` resolver, it has the following fields:

**totalAfterTax**

sum of all invoice_lines.`total_after_tax`

**totalBeforeTax**

sum of all invoice_lines.`total_before_tax`

**totalTaxPercentage**

sum of all invoice_lines.`total_before_tax` / sum of all invoice_lines.`total_after_tax`

**serviceBeforeTax**

sum of all invoice_lines.`total_before_tax`, with items of type `service`

**stockBeforeTax**

sum of all invoice_lines.`total_before_tax`, with items of type `stock`

Also should expose `invoiceLineNode` **totalAfterTax** and **totalBeforeTax**

`invoice_line`.**item_name** should be editable for items of type `service` (in invoice_line mutation)

**Q3** -> Do we want to have a service type item where item_name is not actually editable ?

**Q4** -> Following up from `Q2` what should be exposed mutation wise (apart form `cost/sell_price_per_pack`)

## Sync

We still keep denormalised totals for invoice, and they still be calculated on invoice_line mutations for backwards compatibility with mSupply (they only sync out from remote site), these totals are not used in omSupply.  After some deliberation it was deemed not necessary to map `tax` amount from central to remote (as it's not really used, and would be ok to not translate it for migrating sites).

- [ ] Implement remaining
- [ ] Document

**Comment by andreievg** [comment]
from: https://github.com/openmsupply/remote-server/issues/567

> totalTaxPercentage: maybe just tax percentage? Not sure what a total percentage would refer to?

sure can just have taxPercentage, although it seems trivial to calculate on F/E if totals are provided ?

**Comment by mark-prins** [comment]
🙄  yeah.. but you know how lazy those front end guys are?

was just trying to keep as much logic as possible in the back room and have the front end display what it is given. this is a trivial example, so it doesn't matter which way we go, but that's the motivation

**Comment by andreievg** [comment]
> yeah.. but you know how lazy those front end guys are?

Lol oki, will have it as taxPercentage

**Comment by andreievg** [comment]
Just to sum up

- [ ] Item to have type -> `service`, `stock` (stock_unallocated also but that's for placeholder lines), I think this is translatable from central data
- [ ] total after tax and total before tax to be added to outbound invoice line mutation (populated from stock line if it's linked to invoice line)
- [ ] invoice lines with item of type service have item name as editable 
- [ ] invoice lines with item of type service, stock line not required

Perhaps it's better to add a seperate mutation for service lines at this stage ?  (since there are a lot of variable field that are optional but need to be checked (i.e. stock_line, number_of_packs etc..)

**Comment by andreievg** [comment]
done
