### ISSUE TITLE
Improved logging (e.g. request id in logs)

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/remote-server#570]
There is some tracing crate which seem to be very powerful (https://tracing.rs/tracing/).

Some good examples are here:
https://betterprogramming.pub/production-grade-logging-in-rust-applications-2c7fffd108a6

Alternatively we do our own simple logger, e.g. 
``` rust
struct RequestIdLogger {
   request_id: String
}

impl log::Logger for RequestIdLogger {
   fn log() {...}
}
```
and pass the logger down stream, e.g. 

``` rust 
struct MyService {
   logger: &dyn log::Logger
}

fn gql_endpoint() {
   // this could be put into some logger factory method, e.g. new_request_logger()
   let logger: log::Logger = RequestIdLogger { request_id: rand() };
   
   let service = MyService::new(&logger);
}
```

**Comment by andreievg** [comment]
I think we mentioned that logging is something important for v1

**Comment by andreievg** [comment]
> I think we mentioned that logging is something important for v1

I think the important logging for v1 is different to this issue, I think it was referring to logging of operations (i.e. user  finalised invoice b on date). 

I was wondering, what are the use cases and benefits of using something like the tracing crate, and what was the motivation for this issue

**Comment by clemens-msupply** [comment]
Yes this issue was about simple log messages. The use case would be that we could easily customize what to do with the log messages, e.g. write them to a file, write them to some analytics tool, or just write them std out, or all together...

However, the log crate we are using might be already powerful enough for us since It allows to set a global Logger (once) at startup. For Android we are already using it and log messages are send to the Android logcat.
