### ISSUE TITLE
Dashboard endpoint

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/remote-server#579]
The dashboard section is making use of some queries which aren't currently supported.

![Screen Shot 2021-11-18 at 2 15 49 PM](https://user-images.githubusercontent.com/9192912/142333150-b58b57bd-6ac7-450a-a003-b283bc9d666c.png)

This is an area which I expect will be expanded, as we think of new statistics to add.. for now though what we have is 
- stock count, showing stock which is expired and expiring soon ( for this, I've used within 3 months 🤷  )
- invoices
  - number of outbound to be picked i.e. the count of outbound shipments which are `ALLOCATED`
  - number of inbound created today
  - number of inbound created this week

This is just what I've put together and have implemented in the mock API - can share the schema as well, but I thought that's probably not required? Names and shapes are up for discussion of course - the requirement is just to have something to show on the dashboard. I've used three separate calls, so that each dashboard area can be a separate component.

### Query
```
query invoiceCounts($type: InvoiceNodeType!) {
  invoiceCounts(type: $type) {
    ... on InvoiceCountsConnector {
      __typename
      created {
        today
        thisWeek
      }
      toBePicked
    }
    ... on ConnectorError {
      __typename
      error {
        description
      }
    }
  }
}
```
### Response
With the variables as `{ "type": "OUTBOUND_SHIPMENT" }` the response is:

```
{
    "data": {
        "invoiceCounts": {
            "__typename": "InvoiceCountsConnector",
            "toBePicked": 27
        }
    }
}
```

With the variables as `{ "type": "INBOUND_SHIPMENT" }` the response is:

```
{
    "data": {
        "invoiceCounts": {
            "__typename": "InvoiceCountsConnector",
            "created": {
                "today": 0,
                "thisWeek": 0
            }
        }
    }
}
```

### Query
```
query stockCounts {
  stockCounts {
    ... on StockCountsConnector {
      __typename
      expired
      expiringSoon
    }
    ... on ConnectorError {
      __typename
      error {
        description
      }
    }
  }
}
```

### Response
```
{
    "data": {
        "stockCounts": {
            "__typename": "StockCountsConnector",
            "expired": 0,
            "expiringSoon": 189
        }
    }
}
```

**Comment by mark-prins** [comment]
lowering the priority even though I'm keen to see this in place. We can use the mock service worker to respond to the queries instead, and there's other issues which I think are more urgent.

**Comment by mark-prins** [comment]
bumping up again - not the highest priority, but we do need this in place for demo purposes.

**Comment by mark-prins** [comment]
New request after yesterday's meeting:

A count of the number of items which have low months of stock values. A few things to unpack there:
- aggregation in order to get MOS values
- what is the threshold for 'low months of stock'
- is the threshold configurable for a client?
- is the threshold configurable per item?

And an extra, for bonus points: Some way of showing which actual items are low, and their MOS values.

**Comment by clemens-msupply** [comment]
@mark-prins how is the low month of stock value defined?

**Comment by mark-prins** [comment]
It's something I need to explore with Craig, to get some answers to some of those questions.

As a starting point, I would think to compare the total stock on hand for an item, in a particular store with the `minimum_stock` value in `item_store_join` ..if that is defined for the item.

The common figure that I've seen is to check that an item has 3+ months of stock, given the calculated MOS value and the current stock on hand. I'm wondering if the `3` should be configurable somewhere.. and if that should be per item with a fallback value configured for the store too.

**Comment by clemens-msupply** [comment]
For MOS, do we take a snapshots of all stock every month/day and average over these snapshots?

**Comment by clemens-msupply** [comment]
I changed the invoiceCounts data struct to:

```Typescript
interface InvoiceCounts {
  outbound?: {
    created?: {
       today?: number,
       thisWeek?: number,
    },
    toBePicked?: number
  },
  inbound?: {
    created?: {
       today?: number,
       thisWeek?: number,
    },
  },
}
```
and `invoiceCounts(timezoneOffset?: number)` only takes a timezone parameter now (default is local server time)

@mark-prins  what do you think? should we also rename invoiceCounts -> shipmentCounts?

**Comment by mark-prins** [comment]
> For MOS, do we take a snapshots of all stock every month/day and average over these snapshots?

I wasn't sure if this is asking 'do we currently do this?' or 'should we do this?' 😄 
The 'what we do now' is probably more of a discussion with Andrei who has been heavily involved in this area.. there is an aggregation table in mSupply, and a scheduled process to generate aggregations which runs daily. All data in the table is cleared and recalculated, with the stock on hand values back-calculated by looking at all movements in and out.

There has been talk of moving away from this approach - which is why a discussion would be useful. I don't expect that we'll simply take the aggregation table across or try to replicate it directly.

For the work on the grafana dashboards we have talked about recording snapshots of various data points so that we can plot some historical info. The calculation to determine the current state is usually fairly simple; the calculation for historical data usually more challenging
