### ISSUE TITLE
Stocktakes

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/remote-server#623]
This is a placeholder for stocktake support, I'll leave it up to implementers to create separate issues for sub tasks, as required.

- Query: list of stocktakes
  - Filter by `description` with a text filter
  - Sort by `description`, `date`, `status`
  - Pagination
- Query: stocktake by id
  - Include stocktake lines
  - Sort lines by [ideally, all fields returned]
- Mutation: Create stocktake
- Mutation: Delete stocktake
- Mutation: Update stocktake 
- Mutation: Create stocktake line
- Mutation: Delete stocktake line
- Mutation: Update stocktake line

## Queries
This is what we have implemented within the mock server, to give you an example of where we are heading so far.

### List

```
query MyQuery {
  stocktakes(params: {sort: {key: description}, page: {}, filter: {description: {}}}) {
    ... on NodeError {
      __typename
      error {
        description
        ... on DatabaseError {
          __typename
          description
          fullError
        }
        ... on RecordNotFound {
          __typename
          description
        }
      }
    }
    ... on StocktakeConnector {
      nodes {
        comment
        description
        id
        stocktakeNumber
        stocktakeDate
        lines {
          ... on ConnectorError {
            __typename
            error {
              description
              ... on DatabaseError {
                __typename
                description
                fullError
              }
              ... on PaginationError {
                __typename
                description
                rangeError {
                  description
                  field
                  max
                  min
                }
              }
            }
          }
          ... on StocktakeLineConnector {
            nodes {
              batch
              snapshotPackSize
              snapshotNumPacks
              sellPricePerPack
              itemName
              itemCode
              id
              expiryDate
              countedNumPacks
              costPricePerPack
              comment
              location
            }
            totalCount
          }
        }
        status
      }
      totalCount
    }
  }
}
```

#Stocktake
```
query MyQuery {
  stocktake(id: "") {
    ... on NodeError {
      __typename
      error {
        description
        ... on RecordNotFound {
          __typename
          description
        }
        ... on DatabaseError {
          __typename
          fullError
          description
        }
      }
    }
    ... on StocktakeNode {
      id
      comment
      description
      lines {
        ... on ConnectorError {
          __typename
          error {
            description
            ... on DatabaseError {
              __typename
              description
              fullError
            }
            ... on PaginationError {
              __typename
              description
              rangeError {
                field
                max
                min
                description
              }
            }
          }
        }
        ... on StocktakeLineConnector {
          nodes {
            batch
            costPricePerPack
            countedNumPacks
            expiryDate
            snapshotPackSize
            snapshotNumPacks
            sellPricePerPack
            itemName
            itemCode
            id
            location
            comment
          }
          totalCount
        }
      }
      stocktakeNumber
      stocktakeDate
      status
    }
  }
}
```

### Stocktake
```
mutation MyMutation {
  updateStocktake(input: {id: "", comment: "", description: "", status: DRAFT, stocktakeDate: ""}) {
    ... on NodeError {
      __typename
      error {
        description
        ... on DatabaseError {
          __typename
          description
          fullError
        }
        ... on RecordNotFound {
          __typename
          description
        }
      }
    }
    ... on StocktakeNode {
      id
      comment
      stocktakeNumber
      stocktakeDate
      status
      lines {
        ... on ConnectorError {
          __typename
          error {
            description
            ... on DatabaseError {
              __typename
              description
              fullError
            }
            ... on PaginationError {
              __typename
              description
              rangeError {
                description
                field
                min
                max
              }
            }
          }
        }
        ... on StocktakeLineConnector {
          nodes {
            batch
            costPricePerPack
            countedNumPacks
            snapshotPackSize
            snapshotNumPacks
            sellPricePerPack
            itemName
            itemCode
            id
            expiryDate
          }
          totalCount
        }
      }
      description
    }
  }
}
```

**Comment by andreievg** [comment]
Summary from Zoom 14/12

**New stock_line** 

In case of a fresh install stocktake or stocktake where new batch was found. stocktake_stock_line.id is optional, and is nulled. When stocktake is finalised new batch is created

**Batch or expiry changed but not quantity**

invoice_line has a direction field ('in', 'out', null), when quantity is not changed (but other things have changed) direction is null.

**Snapshot quantity**

When finalising when snapshot quantity is different form current stock_line quantity, an error is returned:
```
__typename: "SnapshotDifferentFromCurrentQuantity" 
stockLines: StockLineConnector
```

**Adjustments**

Inventory Adjustment is created when stocktake is finalised (invoice type INVENTORY_ADJUSTMENT)

Use one adjustment rather then two (use in or out on invoice_line.direction, to determine if it's a reduction or addition).

There is a bit of an issue with using one inventory adjustment, we currently have two names that are auto generated on central server when new data file is created (they are 'reduction' and 'addition'), they are used a name for all inventory adjustment invoices. Ideally another name should be created in central server when new data file is created (and on in migration code for version that is compatibly with omSupply), name called 'inventory adjustment', with some hard coded 'code'. 

Personally i am not a fan of special name records, maybe we can set the name of inventory adjustment record to current store name ? (at least for now, until central server can give use this record)

**Comment by joshxg** [comment]
Thanks @andreievg 

- Is the schema [here](https://github.com/openmsupply/remote-server/pull/654), with the comments and the optional stock line pretty accurate as of now? (Just want to double check against what I have and make any adjustments as needed)
- Can you help me understand what you meant by the central server have two names `addition` and `reduction` and needing a third? I thought the central server has `invad` and not that two others? Is this just backwards?
- If it helps - I think special names are a bit of a smell also. Makes sense to me that the 'other party' of an adjustment is the store itself (and maybe for repacks etc also 🤔 )
- If you're interested in a different POV (feel free to ignore :)) - Is `direction` is replacing `[trans_line]type`? I think it made more sense as `type`, though without this special case, I can definitely see the motivation to rename. However, now we are essentially saying when the trans line direction is null, the type of trans line is a non-stock movement. If it's in addition to `type`, then it might not be needed?

**Comment by mark-prins** [comment]
I understood it to be `[trans_line]type` that we were talking about. The `direction` is actually the `stock_in` and `stock_out` values that are in `type`.

**Comment by clemens-msupply** [comment]
- what was the motivation for shipment_line direction? (aka trans_line, aka invoice_line) e.g. why not use shipment_line::number_of_packs which can be positive or negative?
- Regarding negative stock. There is the scenario that stock has already been allocated but is not on the shelf, i.e. it can't be picked. This means available_number_of_packs gets negative. For this reason, wouldn't it make sense to track the number of allocated stock? This is better because the number of allocated stock is an exact value while available_number has a couple of uncertainties. This would make it more straight forward to calculate available_number_of_packs after a stock take.
- For the snapshot != current_count conflict:
The stock take `count` mismatch is:
`stock_mismatch = count - snapshot`
(Assuming nobody takes stock while the stock is physically counted)
If shipments happen before the stocktake is finalized the current stock count is:
`count_no_stock_take = snapshot + sum(shipment changes)`
If we finalize the stock take we can add the `stock_miss_match` to `count_no_stock_take` which gives:
`count_after_stock_take = snapshot + sum(shipment changes) + count - snapshot = count + sum(shipment changes)`
which is what we want.
There are probably some other things that could go wrong but I guess its good enough to calculate the stock count even if there is a snapshot and current_count mismatch?

Example:
If the currently recorded stock snapshot is `10` and stock take reveals there is only `8` physical stock: `stock_mismatch = 8 - 10 = -2`. Assuming there is an outbound shipment before the stock take is finalized which takes 6 from the stock: `count_with_out_stock_take = 10 - 6 = 4`. Adding the `stock_mismatch` give the correct number of `count_stock = 2`.

**Comment by clemens-msupply** [comment]
There is another problem when the item is missing as well. What should we do in this case?

Does new item and new stock_line creation actually needs to be tight to a stock take? For example, if a user adds missing items and stock_lines during a stock take and the stock take can't be finalized because a cause another recount is needed the user would have to add the same items again.

Similar, if the user finds an expiry date mistake shouldn't it be updated immediately and independent from the stock take? or does somebody needs to double check it first?

Would it be an option to leave new stock_lines on hold till the finalization, or would that mess with other things?

**Comment by andreievg** [comment]
@joshxg 
> Is the schema here, with the comments and the optional stock line pretty accurate as of now? (Just want to double check against what I have and make any adjustments as needed)

Yeah i think it should be pretty accurate

> Can you help me understand what you meant by the central server have two names addition and reduction and needing a third? I thought the central server has invad and not that two others? Is this just backwards?

Sorry my bad, updated my comment, thanks for correction

> If it helps - I think special names are a bit of a smell also. Makes sense to me that the 'other party' of an adjustment is the store itself (and maybe for repacks etc also 🤔 )

I agree, but I think we have an issue with translation at this point, we are somewhat bound by existing schema (maybe it's not a biggy, i think it should be easy done)

> If you're interested in a different POV (feel free to ignore :)) - Is direction is replacing [trans_line]type? I think it made more sense as type, though without this special case, I can definitely see the motivation to rename. However, now we are essentially saying when the trans line direction is null, the type of trans line is a non-stock movement. If it's in addition to type, then it might not be needed?

I was thinking of invoice_line 'type' being `stock`, `unallocated` and `service` (a little bit of denormalisation but It would be easy to expose in api and easier for front end to see in the list of lines what's what), this would mean another field 'direction' for in and out, idk, keen to chat

> Would it be an option to leave new stock_lines on hold till the finalization, or would that mess with other things?

I think it's easier to just have null for new stock_lines in stocktake_line (it also an easy indicator to front end that it's a new stock line ?)

**Comment by andreievg** [comment]
@mark-prins 

> I understood it to be [trans_line]type that we were talking about. The direction is actually the stock_in and stock_out values that are in type.

As per above, i was thinking to use type for something else and use direction, hmm

**Comment by andreievg** [comment]
> what was the motivation for shipment_line direction? (aka trans_line, aka invoice_line) e.g. why not use shipment_line::number_of_packs which can be positive or negative?

I kind of like this, in existing schema it resembles financial system, where figures are always positive, and the type describes direction (debit/credit). Will have to ask Craig about the original motivation for this, also would it mean we do the same for all of the pricing ?

> Regarding negative stock. There is the scenario that stock has already been allocated but is not on the shelf, i.e. it can't be picked. This means available_number_of_packs gets negative. For this reason, wouldn't it make sense to track the number of allocated stock? This is better because the number of allocated stock is an exact value while available_number has a couple of uncertainties. This would make it more straight forward to calculate available_number_of_packs after a stock take.

Hmm, 'available_number_of_packs' = allocated, total_number_of_packs = picked. I can't remember how we do this currently but it makes sense to do stocktake on total_number_of_packs, and in finalisation check that total_number_of_packs still matches snapshot, and also check that we are not reducing below available. (both will result in error). We can expose invoice_lines -> invoices on stock_line (as say allocated invoice_lines), and affected stock_lines are returned as part of the structured error (this would make it easy for f/e to tell user where the problem originates)

> For the snapshot != current_count conflict:
The stock take count mismatch is:
stock_mismatch = count - snapshot
(Assuming nobody takes stock while the stock is physically counted)
If shipments happen before the stocktake is finalized the current stock count is:
count_no_stock_take = snapshot + sum(shipment changes)
If we finalize the stock take we can add the stock_miss_match to count_no_stock_take which gives:
count_after_stock_take = snapshot + sum(shipment changes) + count - snapshot = count + sum(shipment changes)
which is what we want.
There are probably some other things that could go wrong but I guess its good enough to calculate the stock count even if there is a snapshot and current_count mismatch?

> Example:
If the currently recorded stock snapshot is 10 and stock take reveals there is only 8 physical stock: stock_mismatch = 8 - 10 = -2. Assuming there is an outbound shipment before the stock take is finalized which takes 6 from the stock: count_with_out_stock_take = 10 - 6 = 4. Adding the stock_mismatch give the correct number of count_stock = 2.

I think it is how it's currently done in mSupply. But isn't it complex and confusing to the user ? Like, we actually found some stock after invoice was picked and we actually do have 8 physical stock, but it goes to 2 ? The invoice had actually 10 on it not 8, this would cause reduction below zero ? This is a lot to try and communicate to the user and quite a bit more complex in logic

For that reason would prefer to just go with error on finalisation.

**Comment by andreievg** [comment]
> There is another problem when the item is missing as well. What should we do in this case?

> Does new item and new stock_line creation actually needs to be tight to a stock take? For example, if a user adds missing items and stock_lines during a stock take and the stock take can't be finalized because another recount is needed the user would have to add the same items again.

User can create another stocktake for the new items if needed (i.e. stock take can be just for a couple of items) , there is also another type of mini stocktake called inventory adjustment in mSupply, that can be used for add hock additions of stock.

Also typical stocktake should be done when stock is not likely to move (that's why they are typically done outside of business hours in commercial warehouses)

> Similar, if the user finds an expiry date mistake shouldn't it be updated immediately and independent from the stock take? or does somebody needs to double check it first?

Expiry and batch etc is currently editable in stock page in mSupply (so dont' really need a full stock_take to adjust one item)

> Would it be an option to leave new stock_lines on hold till the finalization, or would that mess with other things?

Could potentially do it, i would assume you mean instead of a null on stocktake_line for stock_line ? If we create stock_line for those new lines (to make sure fk constraint on stocktake_line is respected), it would have 0 quantity anyways so won't be able to be used. 

I think it's cleaner to only allow invoice_lines and invoices to ever do any mutations on stock_line (I think this is what Craig was also pointing to).
