### ISSUE TITLE
Inbound shipment service lines

### ISSUE THREAD

**Issue by joshxg** [openmsupply/remote-server#689]
I've noticed we have insert/update/delete for `OutboundServiceLine`, but not `InboundServiceLine`.

For an inbound/supplier invoice in msupply, I can add service charges:

![image](https://user-images.githubusercontent.com/35858975/148340054-4bec042e-15ca-4a50-91f3-6a01803399e0.png)

And the same for an outbound/customer invoice:

![image](https://user-images.githubusercontent.com/35858975/148340501-3a24ca08-29a1-4663-b565-39006d142770.png)

Do we not meant to have service lines for inbounds?

**Comment by joshxg** [comment]
@andreievg  @clemens-msupply 

Shall I @ you guys? Oops too late! 😁

**Comment by clemens-msupply** [comment]
A bit lost. The inbound shipment is a shipment you are receiving, right? does the the receiver adds a service charge? if yes what is this service charge?

**Comment by joshxg** [comment]
> The inbound shipment is a shipment you are receiving, right?

Yup.

> does the the receiver adds a service charge?

They can do, yes. For instance - if the supplier of the goods is not an mSupply user, the recipient of the goods needs to manually create the invoice as the system cannot create one for them automatically. In this example, the user would need to manually add the service charges, if any.

> if yes what is this service charge?

I believe a real example could be transport costs - courier charges or 'extra charges' for 'quick delivery'.

**Comment by andreievg** [comment]
This sounds like it's in V1

**Comment by andreievg** [comment]
Should be in dev now
