### ISSUE TITLE
isAdhoc (or similarly named field) to shipments

### ISSUE THREAD

**Issue by joshxg** [openmsupply/remote-server#691]
As discussed previously, we'd like to change the statuses based on whether the shipment is created for an external supplier (for an inbound shipment - type is facility rather than store). Also, for outbound shipments - though I am not sure there is 'external customers'.. I think we could use the linked requisition to determine this?

**Comment by andreievg** [comment]
Thought to quickly do this, but ended up down a rabbit hole.

>  though I am not sure there is 'external customers'

I've seen a lot of facility type customers, it's a bit hard to have all facilities being a store in the system from the get go, typically we do deployment top down. And some small facilities might never be a store, and maybe some private sector can be supplied through national supply.

> I think we could use the linked requisition to determine this

I would assume that we can't force users to make requisitions, some stock will be pushed to other stores.

Anyways, what i've done is added otherPartyStore to InvoiceNode, which comes from a new field on invoice node, name_store_id, the reason i thought it needs to be a field, is for historic purposes, when looking back statuses should still reflect the options that were there when invoice was created (say if otherParty was a facility and then turned to store)

Also added NameNode->store

**Comment by joshxg** [comment]
Good points.

For reference, I found this method in mSupply which determines if the big red "STOCK TRANSFER" should be displayed, which I suppose is what should determine what we change in the UI?: https://github.com/sussol/msupply/blob/master/Project/Sources/Methods/transactDisplayTransfer.4dm#L28-L43

**Comment by mark-prins** [comment]
which says that if it is a customer invoice, then it is a stock transfer, which means that either 'stock transfer' includes external facilities or that the expectation is that ci & si are only between mSupply controlled facilities.

I thought that it was the latter (ci === stock transfer). We will need to decide / clarify this.

a minor point: the name `name_store_id` isn't helping me understand the intention(!) the use of `otherParty` works for me because it indicates direction - what is the name and what is the store in the new field?

**Comment by andreievg** [comment]
> a minor point: the name name_store_id isn't helping me understand the intention(!) the use of otherParty works for me because it indicates direction - what is the name and what is the store in the new field?

Agree but in DB the other party is just `name`, I personally like other party, but there was a poll awhile ago which resulted in quite a rumble of a conversation and `name` was kept in DB, thus nane_store_id in DB. API has otherParty and otherPartyStore (we'll comment in DB schema about what `name` actually means)

**Comment by mark-prins** [comment]
ah.. I see. thanks
