### ISSUE TITLE
Move graphql tests into graphql crate

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/remote-server#699]
There is not real reason why the graphql tests need to be in the main server crate. Having them in the graphql crate should be a bit more natural.

**Comment by andreievg** [comment]
- [ ] https://github.com/openmsupply/remote-server/pull/853
- [ ] https://github.com/openmsupply/remote-server/pull/854
- [ ] https://github.com/openmsupply/remote-server/pull/855
- [ ] https://github.com/openmsupply/remote-server/pull/856
- [ ] https://github.com/openmsupply/remote-server/pull/857
- [ ] https://github.com/openmsupply/remote-server/pull/858
- [ ] https://github.com/openmsupply/remote-server/pull/859
- [ ] https://github.com/openmsupply/remote-server/pull/860

**Comment by andreievg** [comment]
Should be in dev now
