### ISSUE TITLE
Update sqlx migrations

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/remote-server#71]
Update sqlx migrations with timestamp of first alpha release candidate.

**Comment by clemens-msupply** [comment]
is that needed? migrations might need ordered which makes it hard anyway...

**Comment by wlthomson** [comment]
Oops, good find. This is outdated now.

Looks like we might not necessarily be using sqlx or diesel migrations, so this might be irrelevant anyway.

In either case, sqlx is out, so will close this now.
