### ISSUE TITLE
Store GQL

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/remote-server#715]
have started to use the store endpoint to retrieve a list of stores and I have some requests:

- There's a filter and pagination, but no sort option. Can we have the option to order the results please
- The default sort order is a bit random - hopefully there'd be a sort parameter anyway, even if there is, can you sort results. preferably alpha, case insensitive, by description or name
- There's only `code` and `id` - can I have a `description` as well please

**Comment by andreievg** [comment]
Ended up adding a bit more, and couldn't find description in legacy store, but exposed sorting and filter of joined name

StoreFilterInput
* id
* name
* code
* nameCode

StoreSortFieldInput
* name
* code
* nameCode
