### ISSUE TITLE
Requisition chart queries

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#809]
- [x] #932
- [x] #958
- [x] #963
- [x] #973
- [x] #975
- [x] #977
- [x] #983

Need to get some feedback from stakeholder.

From my understanding, should be able to back data itemStats queries ? 
And maybe get an array of itemStats for periods ?

**Comment by joshxg** [comment]
ref: https://github.com/openmsupply/remote-server/issues/680

**Comment by mark-prins** [comment]
Suggested shape ( thanks @joshxg )

```
itemChartData(itemId: "xxx-xxx")
```

which could return

```
{
    suggestedQuantity:  { soh: number, onOrder: number, suggested: number, inTransit: number },
    consumptionHistory: { amc: number, movingAverage: number, date: string }[],
    stockEvolution: { date: string, projected: number  }[]
}
```

Wondering about where to source the number of days to display - thinking that this is likely configuration and therefore a back-end concern, so we don't need params to specify.

**Comment by andreievg** [comment]
>  consumptionHistory: { amc: number

Would that amc be consumption rather then AMC, and movingAverage is the AMC ?

**Comment by andreievg** [comment]
>     stockEvolution: { date: string, projected: number  }[]

Also need the stock history to display `past`

**Comment by andreievg** [comment]
maybe like this ?
 `suggestedQuantity:  { amc: number, target: number, soh: number, suggested: number } `

**Comment by mark-prins** [comment]
> suggestedQuantity: { amc: number, target: number, soh: number, suggested: number }

the `target` is useful, I've needed to calculate it to make the bar charts. The values of `inTransit` and `onOrder` would be great to have too; could be later, I've just left them out for now. `amc` is available on `itemStats` - good to have in here though

**Comment by mark-prins** [comment]
@andreievg I've implemented the mock, but have had to munge the data to get it into a format that's easily plottable.

I used `isHistoric` and a `value` field instead of having separate fields for `historicStockOnHand` and `projectedStockOnHand`

this is what I've done to map the data:

```
const data =
    draftLine?.chartData?.stockEvolution.nodes
      .map(node => ({
        date: new Date(node.date),
        value: node.historicStockOnHand ?? node.projectedStockOnHand ?? 0,
        isHistoric: node.historicStockOnHand !== null,
        max: draftLine.itemStats.averageMonthlyConsumption * maxMonthsOfStock,
        min: draftLine.itemStats.averageMonthlyConsumption * minMonthsOfStock,
      }))
      .sort(dateSorter) ?? [];
```

couple of parts which I wonder if it's possible to do:
- have a single value field and a bool to indicate historic
- the order was coming through strangely.. could it be sorted by date?
- I've sourced the `max` & `min` line data.. could that be included?

**Comment by andreievg** [comment]
> I've sourced the max & min line data.. could that be included?

Would they be historic max and min ? (btw also available in suggestedQuantityCalculation)

I've [updated](https://github.com/openmsupply/remote-server/issues/958)

**Comment by mark-prins** [comment]
legend! thanks Andrei
Good thought about historic max & min.. I've just shown a line for the current value of number of months min & max times the amc, that's what I understand the intention was. just to show users how the mos values compare to historical data

**Comment by andreievg** [comment]
Oki will be set as current max/min in implementation
