### ISSUE TITLE
ServiceLine questions!

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/remote-server#847]
@mark-prins @andreievg @clemens-msupply 

I'm confused in regard to the service line mutations/implementation.

I'm going to [*try*] clearly describe my understanding and hopefully this will allow someone to highlight exactly where my understanding is wrong.

## Assumptions
1. mSupply has two concepts service items and service charges. 
2. I understood we were to implement *service charges* in omSupply, with a change that we would add multiple *service charges*, rather than the single service charge we can currently add within mSupply. 
3. Right now, the mutations *require* the ID of a *service item*, so seems that the implementation is *service items*. [Though, service items in mSupply can be added to inbound shipments and we currently only have the implementation for outbound shipments]

If we are implementing *service items*, we will need some slight adjustments.. specifically, the ability to query or determine if an item is a service item. Currently the type of an item is not exposed.

### Service items
Service items I have tried to find details on and have asked about this concept but I have not been able to get a clear understanding.

From looking at code:
- There is a pref to allow a user to use service items
- Service items (type_of = service) can be added to supplier invoices when allowed through the pref.
- Note: I've not been able to create a service item without hacking at the `record browser` and 'manually' setting the `type_of` field. I've also not been able to give my store visibility of the 'special item' `service charges` through the UI in mSupply
- My assumption about the use case here is to have static/defined service charges.

### Service charges
- Two fields on a `transact` `service_price` and `service_descrip` which are able to be given arbitrary values
- My assumption about the use case here is to have dynamic service charges.

SI:
<img width="474" alt="image" src="https://user-images.githubusercontent.com/35858975/155870227-922b72ba-29de-4faf-843d-86fa578e8b5e.png">
CI:
<img width="709" alt="image" src="https://user-images.githubusercontent.com/35858975/155870234-89045716-ae05-4649-b2a9-a8c35429efef.png">

**Comment by mark-prins** [comment]
Summary from today's discussion:
- make itemId optional, if not specified the API uses the default service item
- add `type` to filter for `Item`  
- add `type` to `Item`

**Comment by andreievg** [comment]
I am pretty sure the changes have been done, closing
