### ISSUE TITLE
Make sure all basic fields are exposed in query filters and sorts for all types

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#867]

**Comment by andreievg** [comment]
@roxy-dao this will be good to do also, thank you

**Comment by roxy-dao** [comment]
- Unexposed fields
  - Invoices (Filter by Pricing Rows too?)
    - Filter
      - [ ] transportReference
      - [ ] colour
      - [ ] onHold
      - [ ] nameId
      - [ ] userId
    - Sort
      - [ ] theirReference
      - [ ] transportReference
      - [ ] colour
  - Items
    - Sort
      - [ ] type
   - Locations
    - Filter
      - [ ] onHold
  - Requisitions
    - Filter
      - [ ] nameId
      - [ ] userId
      - [ ] linkedRequisitionId
      - [ ] expectedDeliveryDate
      - [ ] maxMonthsOfStock
      - [ ] minMonthOfStock
      - [ ] name (NameRow)
      - [ ] code (NameRow)
      - [ ] isCustomer (NameRow)
      - [ ] isSupplier (NameRow)
    - Sort
      - [ ] expectedDeliveryDate
      - [ ] colour
      - [ ] theirReference
      - [ ] maxMonthsOfStock
      - [ ] minMonthsOfStock
      - [ ] code (name_row)
  - Stocktakes (can add to #981 )
    - Filter
      - [ ] userId
      - [ ] isLocked
      - [ ] inventoryAdjustmentId

**Comment by andreievg** [comment]
@roxy-dao, I've updated above, thanks for compiling the list

**Comment by roxy-dao** [comment]
> @roxy-dao, I've updated above, thanks for compiling the list

Thanks 😄
