### ISSUE TITLE
Cross team meeting 08/03

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#879]
* Stocktake date input, is it date or date and time ?

**Comment by joshxg** [comment]
- https://github.com/openmsupply/openmsupply-client/issues/385

**Comment by mark-prins** [comment]
Printing. We talked about adding a dummy endpoint to the API which would return a PDF. Could we implement that before doing the real printing work?
- https://github.com/openmsupply/openmsupply-client/issues/806

Status of this one?
- https://github.com/openmsupply/openmsupply-client/issues/827

**Comment by joshxg** [comment]
<img width="216" alt="image" src="https://user-images.githubusercontent.com/35858975/157135546-a1c22b2f-9403-407f-9582-030b2f2905e0.png">

**Comment by joshxg** [comment]
This week:
- Requisition charts
- Printing mock 
- Small API changes [ Tax on invoice line, sorting of stores ]
- Transport data https://github.com/openmsupply/remote-server/issues/591
- User.availableStores mock

Not doing
- Transaction categories

Next week:
- Detail views

Notes: 
- Tax on invoice lines made to be `TaxInput`
- Sent number of packs on invoice lines needs to be investigated ( @andreievg ?)
- allocatePlaceholder mutation didn't get prioritised
- Users created by didn't get prioritised

**Comment by mark-prins** [comment]
Just to elaborate on the above:
- Users.availableStores can return a list of all stores-all users for now
- The users createdBy can make use of the `user_account` table, so we don't need to wait for users to be supported by central server

Priorities in general:
- Sync config ahead of supplier returns & customer credits

Notes: 
- activity log in conforma which makes use of triggers to record user actions

**Comment by andreievg** [comment]
Don't push for now, until we have a full circle automated test for push and pull

**Comment by joshxg** [comment]
Forgot from last week:

- Need confirmation on this feature: https://github.com/openmsupply/openmsupply-client/issues/582

**Comment by andreievg** [comment]
looks like everything outstanding that's mentioned here has placeholder issue
