### ISSUE TITLE
allocatePlaceholder mutation

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/remote-server#885]
- [x] #940
- [x] #949
- [x] #951
- [x] #956
- [x] Make sure on hold lines are not used in allocation

😁 

A user can select lines and perform an `Allocate Stock` action:

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/35858975/156898068-0e757d75-a651-4b2c-98cf-05d0685c7322.png">
[drop down would have a new action]

- Allocates any unallocated packs to:
    - Lines in FEFO order - creating new lines where needed.
    - Does NOT allocate to expired lines
    - Does NOT allocate to lines on hold

A new mutation: `allocatePlaceholder(id: ids of invoice line, packSize?: number)`

- Able to pass an id of an invoice line and optional pack size
- Allocates the placeholder quantity to the passed pack size, or if none passed, to any pack size. 
- Also added to batch mutation. If the choice is between bulk and single, bulk is preferred (Suggesting a single for possible use cases in the future, current use case is for bulk)

Responds with: I think the lines which were touched in the allocation process, but unsure what the UI will display yet

Other notes:
- mSupply method for doing this: https://github.com/sussol/msupply/blob/master/Project/Sources/Methods/trans_placeholder_lines_issue.4dm
- found here in the ui: 
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/35858975/156899025-c0687ff9-c606-40fe-bb41-b437ea9db4ed.png">

**Comment by andreievg** [comment]
@joshxg, Thanks for the summary, only question is pack size allocation, not sure what you mean, can discuss in our meeting.

Also I don't think we should be doing fractional quantity like we do in mSupply (can see total quantities being messed up by fractions), instead would rather an optional parameter 'split packs' without it we just allocate in fefo by pack size quantities, and with it auto split pack is generated (v2)

**Comment by joshxg** [comment]
Yes I am not so sure about the pack size, but I should have been clearer in my intention:

At the moment when add/editing an item in an outbound, you can select the pack size for which you want to auto-allocate  (FEFO) to:

![image](https://user-images.githubusercontent.com/35858975/158681992-a30b7cca-4948-48b3-aa6a-d34bfa70c43f.png)

Currently there's no 'allocate placeholder' button.

I thought that if there was a mutation which was doing placeholder allocation for bulk lines, then we could potentially also use it for an 'allocate placeholder' button in this modal also. If it was in this modal, a pack size could be passed.

However, this does get a bit messy with saving etc etc.. so.. maybe not! Will pass the buck to @mark-prins 😁
