### ISSUE TITLE
Missing translation fields in mSupply

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/remote-server#901]
Below is a list of required column at the central server DB to backup new omSupply columns.

Columns annotated with Null means they are optional in omSupply (don't know if it makes a different in mSupply)
NaiveDateTime: is a UTC date+time variable. omSupply would send it as an iso string (e.g. "2011-10-05T14:48:00.000Z") in the push json object.

## trans_line:
- [ ] om_item_code: String
- [ ] om_tax: Null Float
- [ ] om_total_before_tax: Float
- [ ] om_total_after_tax: Float

## transact:
- [x] ~~om_name_store_id: Null String~~ (can actually be deduced)
- [ ] om_created_datetime: NaiveDateTime (maps to entry date and time)
- [ ] om_allocated_datetime: Null NaiveDateTime
- [ ] om_picked_datetime: Null NaiveDateTime
- [ ] om_shipped_datetime: Null NaiveDateTime
- [ ] om_delivered_datetime: Null NaiveDateTime
- [ ] om_verified_datetime: Null NaiveDateTime
- [ ] om_status field: String (currently not a one to one mapping)
- [ ] om_type field: String (inventory adjustment is missing) OR add a type inventory adjustment to mSupply
- [ ] om_colour: String

## requisition:
- [ ] om_created_datetime: NaiveDateTime
- [ ] om_sent_datetime:  Null NaiveDateTime
- [ ] om_finalised_datetime: Null NaiveDateTime
- [ ] om_max_months_of_stock: Float (exiting daysToSupply integer value might loose precision if fractions of a month are specified)
- [ ] om_status; String (not a one to one mapping)
- [ ] om_colour: String

## requisition_line:
- [x] ~~ om_average_monthly_consumption: Float~~ use daily_usage

## stocktake:
- [ ] om_created_datetime: NaiveDateTime
- [ ] om_finalised_datetime:  Null NaiveDateTime

## stocktake_line:
- [ ] om_note: Null String

## name_store_join:
- [ ] om_name_is_customer: bool
- [ ] om_name_is_supplier: bool

**Comment by andreievg** [comment]
Looks great ! Thanks

I have some comments, I think it's better to introduce new fields as you've mentioned, but an alternative

>  om_type field: String (inventory adjustment is missing)

Could add a new type to mSupply also. If we add new field we would also  need to map a type of inventory adjustment to existing mSupply type (i guess pick ci or si)

> om_name_store_id: Null String

Could deduce with existing pull logic

> om_average_monthly_consumption: Float

Could just use daily_usage,  If we add new field we would also need to populate daily_usage
