### ISSUE TITLE
Cross team meeting 10/03

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/remote-server#903]
- Need confirmation on this feature: https://github.com/openmsupply/openmsupply-client/issues/582 ( [from comment](https://github.com/openmsupply/remote-server/issues/879#issuecomment-1062412087) )
- response requisition: can we display customer soh? without a re-query? ( [comment](https://github.com/openmsupply/openmsupply-client/issues/564#issuecomment-1062476106) )

**Comment by mark-prins** [comment]
@andreievg - any thoughts on customer SoH?   

mSupply has this in `[requisition_line]stock_on_hand` which seems to be the customer soh, even though the naming is confusing.. and 'our' soh is calculated using `item_get_stock_for_store()` 🤷

**Comment by andreievg** [comment]
I've made a comment in https://github.com/openmsupply/openmsupply-client/issues/564#issuecomment-1063535854, i am   wondering if looking at linked requisition line item stats is enough

**Comment by mark-prins** [comment]
Just noticed that one - thanks. linked requisition line stats is smart, will give that a go 😄

**Comment by andreievg** [comment]
closing, although don't have a placeholder issue for creating stocktake with a selection of items created from complex filtering, this is technically possible with stocktake batch mutation
