### ISSUE TITLE
tax_percentage

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/remote-server#907]
- [x] add invoice line node test
- [x] use PricingNode
- [x] untypo

https://github.com/openmsupply/remote-server/blob/d846df7edd28146206217cc0020c1bf34b8380ad/graphql/types/src/types/invoice_line.rs#L122-L123

Should be tax_percentage

Also I find it odd that invoice has an `InvoicePricingNode` but `InvoiceLine` has the fields flattened. I reckon both should be the same 😁

**Comment by andreievg** [comment]
As part of this issue also implementing test for InvoiceLineNode

**Comment by joshxg** [comment]
Maybe flattened is better. I'm not sure. I just like consistent 🤣

**Comment by andreievg** [comment]
> I just like consistent

Same
