### ISSUE TITLE
Cross team meeting summary 15/03

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#931]
From last week (https://github.com/openmsupply/remote-server/issues/879).

**Immediate** from last week `this week` section (https://github.com/openmsupply/remote-server/issues/879).

- [ ] https://github.com/openmsupply/remote-server/issues/809 (do mock asap)
- [x] https://github.com/openmsupply/remote-server/issues/591
- [ ] User availableStores (and default store), on login and me endpoint to return userNode with default store and resolvers for availableStores (in PR)

When above is done look at https://github.com/openmsupply/openmsupply-client/issues/827 and re-priorities

- [ ] Inbound shipment pricing updates same as outbound shipment
- [x] Investigate hanging
- [x] Investigate user not being associated
- [x] allocatePlaceholder
- [ ] [masterList for outbound shipments](https://github.com/openmsupply/remote-server/issues)
- [ ] Sent number of packs on invoice lines needs to be investigated (should expose linked invoice line, and in transfers make sure send number of packs is set for backward compatibility) (added to https://github.com/openmsupply/remote-server/issues/706)

Even though user association with records was not priorities, it was done in last week, generic `entered by` caption might not be accurate based on what's been implemented, to be accurate the following captions should apply:

`Request Requisition` -> entered by
`Outbound Shipment` -> entered by
`Stocktake` -> entered by
`Response Requisition` -> edited by
`Inbound Shipment` -> edited by

Had another chat about pricing, still not sure what the conclusion was, but I think we agreed that if outbound shipment is fine as is, it should just be replicated for inbound shipment.

**Comment by CarlosNZ** [comment]
> Even though user association with records was not priorities, it was done in last week, generic `entered by` caption might not be accurate based on what's been implemented, to be accurate the following captions should apply:

@andreievg -- Would you be open to a more comprehensive "history" log that can capture the full history of changes? You can keep a separate "event_log" table with fields such as:
- timestamp
- userId
- table (or "type": invoice, user, requisition etc)
- recordId
- eventType: (enum: CREATE, EDIT, DELETE)
- value (what it was changed to, if relevant)
- details (JSON object containing all relevant info pertaining to the event. e.g. previous value, full item list if an invoice -- however much detail you want to preserve a history of)

We did something similar for conforma -- different requirements, obviously, but might have some conceptual overlap perhaps?

**Comment by andreievg** [comment]
I like the idea, would be good to chat about it after V1, a couple of possible show stoppers:
* Potentially a lot of data to sync and a lot more data in DB
* More load in triggers (have to compare each field or use JSON methods that are not available in sqlite) OR a bit more logic in services

I think it's best to ask the stakeholders about the use cases (what sort of information regarding record changes needs to be presented to user).

**Comment by CarlosNZ** [comment]
> I think it's best to ask the stakeholders about the use cases (what sort of information regarding record changes needs to be presented to user).

Yeah, it's really only useful if you need a complete log of who changed what and when. But probably not needed for V1.

**Comment by mark-prins** [comment]
thanks @CarlosNZ - good thought!

we have a log on most of the mock up screens, as something that has come across from mSupply - so we will need an activity log of some form. The requirement is currently in at number 7 in the [omSupply v1 priorities spreadsheet](https://docs.google.com/spreadsheets/d/1aVBBPH5XCNkDIv-LAW0vgQ4dZpgixxxe3OqLVwIqNx4/edit#gid=0)

haven't made issues for it yet though, am expecting that the activity log will be v1+ now.

**Comment by andreievg** [comment]
Closing, i've added extra issues to record outstanding things
