### ISSUE TITLE
Response (Customer) requisitions: set supplied quantity

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/remote-server#942]
There is this requirement for response requisitions:

> Set automatically set the quantity to be supplied for every line to be equal to the requested quantity

there is no batch mutation for response reqs, and no mutation which would set the supplied based on the requested.
The closest is `useSuggestedQuantity` which sets the `requested` to be the `suggested`.

Could we have either a batch, or a mutation? prefer a mutation.. but don't mind.

Ref: [#1055](https://github.com/openmsupply/openmsupply-client/issues/1055)

**Comment by andreievg** [comment]
There is supplyRequestedQuantity mutation, but that's for the whole invoice, should it have an array of line_ids as optional ?
Similar useSuggestQuantity ?

**Comment by joshxg** [comment]
This is me in the front and andrei in the back??

<img src="https://media1.giphy.com/media/nPxVvyTWo1aIU/200.gif?cid=5a38a5a26bj8kk649z5reg8n2t2torixgn1qui8y78jjhesc&rid=200.gif&ct=g"/>



I'd put changing the already existing mutations as low priority (but yes, helpful)

**Comment by mark-prins** [comment]
ah! missed that - thanks. 
yeah `supplyRequestedQuantity` will do for now, I was thinking of all lines at this stage. later (maybe) we do a per line selection version..
