### ISSUE TITLE
Not all queries are checking auth token

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/remote-server#971]
Most queries don't require an auth token, and I understood that all queries & mutations should now?

I've only found requisitions & stocktakes which requires the auth token, and the mutation to allocate placeholder stock.
These ones require the token:

- requisition
- requisitionByNumber
- requisitions
- stocktake
- stocktakeByNumber
- stocktakes

haven't tested all the mutations yet.. that's harder than just querying 😉

**Comment by clemens-msupply** [comment]
I created a new ticket for testing the endpoints:
https://github.com/openmsupply/remote-server/issues/1025
