### ISSUE TITLE
Stocktake query -- missing sort keys

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/remote-server#981]
The stocktakes endpoint is currently only allowing three fields (see screenshot) as sort keys. We also need the other fields as sortable fields, namely `stocktakeNumber`, `comment`, `description`, `stocktakeDate`.

<img width="294" alt="Screen Shot 2022-03-28 at 8 32 49 PM" src="https://user-images.githubusercontent.com/5456533/160348717-f22d2d41-95e5-45cd-a750-662596491e45.png">

**Comment by andreievg** [comment]
@roxy-dao, this will be a good issue to have a look at, basically exposing all sort fields and all filters. Don't think we need to add any more tests for new sort/filter fields, if can just give it a quick manual test when you done, that would be great
