### ISSUE TITLE
Rename Name -> NameStoreJoin

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/remote-server#985]
- NameQueryRepository is about name_store_joins; rename it and related type to NameStoreJoinRepository.

- NameQueryRepository also has a filter:
```
        // Filter out name for current store
        query = query.filter(store_dsl::id.ne(store_id).or(store_dsl::id.is_null()));
```
This prevents to query name_store_joins for the specified store_id. This filter might be better applied in the service layer where it is needed and keep the repo more general purpose.

- In the graphql, the StoreNode::name is a bit misleading since it returns a name_store_join. Document it and/or rename it, e.g. 
```rust
/// Returns a StoreNode's relation to another store
fn StoreNode::name_store_relation(store_id);
```

**Comment by andreievg** [comment]
We can just make another filter `is_current_store_name` for `query.filter(store_dsl::id.ne(store_id).or(store_dsl::id.is_null()));`

It's technically Name repository, with name properties being joined (name_store_join), it is suppose to return all names even if they don't have name_store_join and allow filtering by name_store_join fields and name field. If it's renamed to name_store_join, it still won't be accurate (as names that don't have name_store_join are returned)
