### ISSUE TITLE
Initial Sync

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#996]
I would assume this is the desired behaviour:

When remote server is not initilised, only one end point is available, where sync settings can be entered. After entering sync settings we try to initilise the server (with another endpoint indicating syncing status). 

After initilisation, sync settings end point is available with minor changes (intervals, and maybe ability to wiped data to start over ?).

Related:
- [x] https://github.com/openmsupply/remote-server/issues/790
- [x] https://github.com/openmsupply/remote-server/issues/789

**Comment by clemens-msupply** [comment]
Duplicated by: https://github.com/openmsupply/remote-server/issues/1015
